#!/usr/bin/env bash
# create-test-db - Rapidly Test Database Provisioning
# Version: 1.0.0-rapidly
#
# Creates the Rapidly test database if it does not already exist.
# Requires PostgreSQL client tools (psql) to be available in PATH.

set -e

user="rapidly"
password="rapidly"
host="localhost"
test_database="rapidly_test"

echo "[rapidly] Checking for test database '${test_database}'..."

if ! PGPASSWORD=$password psql -h "$host" -U "$user" -d "postgres" -tAc "SELECT 1 FROM pg_database WHERE datname='$test_database'" | grep -q 1; then
  echo "[rapidly] Creating database ${test_database}..."
  PGPASSWORD=$password psql -h "$host" -U "$user" -d "postgres" -c "CREATE DATABASE $test_database;"
  echo "[rapidly] Database ${test_database} created successfully."
else
  echo "[rapidly] Database $test_database already exists."
fi
