/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * CustomerPortalUsageSettings
     * @description Visibility toggle for usage data in the customer portal.
     */
    CustomerPortalUsageSettings: {
      /** Show */
      show: boolean
    }
    /** CustomerSessionCodeEmail */
    CustomerSessionCodeEmail: {
      /**
       * Template
       * @default customer_session_code
       * @constant
       */
      template: 'customer_session_code'
      props: components['schemas']['CustomerSessionCodeProps']
    }
    /** CustomerSessionCodeProps */
    CustomerSessionCodeProps: {
      /** Email */
      email: string
      workspace: components['schemas']['Workspace']
      /** Code */
      code: string
      /** Code Lifetime Minutes */
      code_lifetime_minutes: number
      /** Url */
      url: string
    }
    /** EmailUpdateEmail */
    EmailUpdateEmail: {
      /**
       * Template
       * @default email_update
       * @constant
       */
      template: 'email_update'
      props: components['schemas']['EmailUpdateProps']
    }
    /** EmailUpdateProps */
    EmailUpdateProps: {
      /** Email */
      email: string
      /** Token Lifetime Minutes */
      token_lifetime_minutes: number
      /** Url */
      url: string
    }
    /** FileShareDownloadCompletedNotificationPayload */
    FileShareDownloadCompletedNotificationPayload: {
      /** File Name */
      file_name: string
    }
    /** FileSharePaymentReceivedNotificationPayload */
    FileSharePaymentReceivedNotificationPayload: {
      /** File Name */
      file_name: string
      /** Formatted Amount */
      formatted_amount: string
    }
    /** FileShareSessionExpiredNotificationPayload */
    FileShareSessionExpiredNotificationPayload: {
      /** File Name */
      file_name: string
    }
    /** LoginCodeEmail */
    LoginCodeEmail: {
      /**
       * Template
       * @default login_code
       * @constant
       */
      template: 'login_code'
      props: components['schemas']['LoginCodeProps']
    }
    /** LoginCodeProps */
    LoginCodeProps: {
      /** Email */
      email: string
      /** Code */
      code: string
      /** Code Lifetime Minutes */
      code_lifetime_minutes: number
    }
    /** MaintainerCreateAccountNotificationPayload */
    MaintainerCreateAccountNotificationPayload: {
      /** Workspace Name */
      workspace_name: string
      /** Url */
      url: string
    }
    /** NotificationCreateAccountEmail */
    NotificationCreateAccountEmail: {
      /**
       * Template
       * @default notification_create_account
       * @constant
       */
      template: 'notification_create_account'
      props: components['schemas']['MaintainerCreateAccountNotificationPayload']
    }
    /** NotificationFileShareDownloadCompletedEmail */
    NotificationFileShareDownloadCompletedEmail: {
      /**
       * Template
       * @default notification_file_share_download_completed
       * @constant
       */
      template: 'notification_file_share_download_completed'
      props: components['schemas']['FileShareDownloadCompletedNotificationPayload']
    }
    /** NotificationFileSharePaymentReceivedEmail */
    NotificationFileSharePaymentReceivedEmail: {
      /**
       * Template
       * @default notification_file_share_payment_received
       * @constant
       */
      template: 'notification_file_share_payment_received'
      props: components['schemas']['FileSharePaymentReceivedNotificationPayload']
    }
    /** NotificationFileShareSessionExpiredEmail */
    NotificationFileShareSessionExpiredEmail: {
      /**
       * Template
       * @default notification_file_share_session_expired
       * @constant
       */
      template: 'notification_file_share_session_expired'
      props: components['schemas']['FileShareSessionExpiredNotificationPayload']
    }
    /** OAuth2LeakedClientEmail */
    OAuth2LeakedClientEmail: {
      /**
       * Template
       * @default oauth2_leaked_client
       * @constant
       */
      template: 'oauth2_leaked_client'
      props: components['schemas']['OAuth2LeakedClientProps']
    }
    /** OAuth2LeakedClientProps */
    OAuth2LeakedClientProps: {
      /** Email */
      email: string
      /** Token Type */
      token_type: string
      /** Client Name */
      client_name: string
      /** Notifier */
      notifier: string
      /** Url */
      url: string
    }
    /** OAuth2LeakedTokenEmail */
    OAuth2LeakedTokenEmail: {
      /**
       * Template
       * @default oauth2_leaked_token
       * @constant
       */
      template: 'oauth2_leaked_token'
      props: components['schemas']['OAuth2LeakedTokenProps']
    }
    /** OAuth2LeakedTokenProps */
    OAuth2LeakedTokenProps: {
      /** Email */
      email: string
      /** Client Name */
      client_name: string
      /** Notifier */
      notifier: string
      /** Url */
      url: string
    }
    /**
     * PresentmentCurrency
     * @enum {string}
     */
    PresentmentCurrency:
      | 'aud'
      | 'brl'
      | 'cad'
      | 'chf'
      | 'eur'
      | 'inr'
      | 'gbp'
      | 'jpy'
      | 'sek'
      | 'usd'
    /** WebhookEndpointDisabledEmail */
    WebhookEndpointDisabledEmail: {
      /**
       * Template
       * @default webhook_endpoint_disabled
       * @constant
       */
      template: 'webhook_endpoint_disabled'
      props: components['schemas']['WebhookEndpointDisabledProps']
    }
    /** WebhookEndpointDisabledProps */
    WebhookEndpointDisabledProps: {
      /** Email */
      email: string
      workspace: components['schemas']['Workspace']
      /** Webhook Endpoint Url */
      webhook_endpoint_url: string
      /** Dashboard Url */
      dashboard_url: string
    }
    /** Workspace */
    Workspace: {
      /**
       * Created At
       * Format: date-time
       * @description Creation timestamp of the object.
       */
      created_at: string
      /**
       * Modified At
       * @description Last modification timestamp of the object.
       */
      modified_at: string | null
      /**
       * Id
       * Format: uuid4
       * @description The ID of the object.
       */
      id: string
      /**
       * Name
       * @description Workspace name shown in checkout, customer portal, emails etc.
       */
      name: string
      /**
       * Slug
       * @description Unique workspace slug in checkout, customer portal and credit card statements.
       */
      slug: string
      /**
       * Avatar Url
       * @description Avatar URL shown in customer portal, emails etc.
       */
      avatar_url: string | null
      /**
       * Email
       * @description Public support email.
       */
      email: string | null
      /**
       * Website
       * @description Official website of the workspace.
       */
      website: string | null
      /**
       * Socials
       * @description Links to social profiles.
       */
      socials: components['schemas']['WorkspaceSocialLink'][]
      /** @description Current workspace status */
      status: components['schemas']['WorkspaceStatus']
      /**
       * Details Submitted At
       * @description When the business details were submitted.
       */
      details_submitted_at: string | null
      /** @description Default presentment currency. Used as fallback in checkout and customer portal, if the customer's local currency is not available. */
      default_presentment_currency: components['schemas']['PresentmentCurrency']
      /** @description Workspace feature settings */
      feature_settings: components['schemas']['WorkspaceFeatureSettings'] | null
      /** @description Settings related to notifications */
      notification_settings: components['schemas']['WorkspaceNotificationSettings']
      /** @description Settings related to customer emails */
      customer_email_settings: components['schemas']['WorkspaceCustomerEmailSettings']
      /** @description Settings related to the customer portal */
      customer_portal_settings: components['schemas']['WorkspaceCustomerPortalSettings']
    }
    /** WorkspaceAccessTokenLeakedEmail */
    WorkspaceAccessTokenLeakedEmail: {
      /**
       * Template
       * @default workspace_access_token_leaked
       * @constant
       */
      template: 'workspace_access_token_leaked'
      props: components['schemas']['WorkspaceAccessTokenLeakedProps']
    }
    /** WorkspaceAccessTokenLeakedProps */
    WorkspaceAccessTokenLeakedProps: {
      /** Email */
      email: string
      /** Workspace Access Token */
      workspace_access_token: string
      /** Notifier */
      notifier: string
      /** Url */
      url: string
    }
    /** WorkspaceAccountUnlinkEmail */
    WorkspaceAccountUnlinkEmail: {
      /**
       * Template
       * @default workspace_account_unlink
       * @constant
       */
      template: 'workspace_account_unlink'
      props: components['schemas']['WorkspaceAccountUnlinkProps']
    }
    /** WorkspaceAccountUnlinkProps */
    WorkspaceAccountUnlinkProps: {
      /** Email */
      email: string
      /** Workspace Kept Name */
      workspace_kept_name: string
      /** Workspaces Unlinked */
      workspaces_unlinked: string[]
    }
    /**
     * WorkspaceCustomerEmailSettings
     * @description Which transactional emails are sent to the org's customers.
     */
    WorkspaceCustomerEmailSettings: {
      /** Payment Confirmation */
      payment_confirmation: boolean
    }
    /**
     * WorkspaceCustomerPortalSettings
     * @description Customer-portal UI toggles.
     */
    WorkspaceCustomerPortalSettings: {
      usage: components['schemas']['CustomerPortalUsageSettings']
    }
    /** WorkspaceFeatureSettings */
    WorkspaceFeatureSettings: {
      /**
       * Member Model Enabled
       * @description If this workspace has the Member model enabled
       * @default false
       */
      member_model_enabled: boolean
      /**
       * Tinybird Read
       * @description If this workspace reads from Tinybird
       * @default false
       */
      tinybird_read: boolean
      /**
       * Tinybird Compare
       * @description If this workspace compares Tinybird results with database
       * @default false
       */
      tinybird_compare: boolean
    }
    /** WorkspaceInviteEmail */
    WorkspaceInviteEmail: {
      /**
       * Template
       * @default workspace_invite
       * @constant
       */
      template: 'workspace_invite'
      props: components['schemas']['WorkspaceInviteProps']
    }
    /** WorkspaceInviteProps */
    WorkspaceInviteProps: {
      /** Email */
      email: string
      /** Workspace Name */
      workspace_name: string
      /** Inviter Email */
      inviter_email: string
      /** Invite Url */
      invite_url: string
    }
    /**
     * WorkspaceNotificationSettings
     * @description Which internal notifications the org admin receives.
     */
    WorkspaceNotificationSettings: {
      /** New Payment */
      new_payment: boolean
    }
    /** WorkspaceReviewedEmail */
    WorkspaceReviewedEmail: {
      /**
       * Template
       * @default workspace_reviewed
       * @constant
       */
      template: 'workspace_reviewed'
      props: components['schemas']['WorkspaceReviewedProps']
    }
    /** WorkspaceReviewedProps */
    WorkspaceReviewedProps: {
      /** Email */
      email: string
      workspace: components['schemas']['Workspace']
    }
    /** WorkspaceSocialLink */
    WorkspaceSocialLink: {
      /** @description The social platform of the URL */
      platform: components['schemas']['WorkspaceSocialPlatforms']
      /**
       * Url
       * Format: uri
       * @description The URL to the workspace profile
       */
      url: string
    }
    /**
     * WorkspaceSocialPlatforms
     * @description Supported social profile platforms.
     * @enum {string}
     */
    WorkspaceSocialPlatforms:
      | 'x'
      | 'github'
      | 'facebook'
      | 'instagram'
      | 'youtube'
      | 'tiktok'
      | 'linkedin'
      | 'other'
    /**
     * WorkspaceStatus
     * @description Onboarding / review lifecycle stages.
     * @enum {string}
     */
    WorkspaceStatus:
      | 'created'
      | 'onboarding_started'
      | 'initial_review'
      | 'ongoing_review'
      | 'denied'
      | 'active'
    /** WorkspaceUnderReviewEmail */
    WorkspaceUnderReviewEmail: {
      /**
       * Template
       * @default workspace_under_review
       * @constant
       */
      template: 'workspace_under_review'
      props: components['schemas']['WorkspaceUnderReviewProps']
    }
    /** WorkspaceUnderReviewProps */
    WorkspaceUnderReviewProps: {
      /** Email */
      email: string
      workspace: components['schemas']['Workspace']
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
