import { LegalPage } from '@/components/Landing/LegalPage'
import { CONFIG } from '@/utils/config'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Use',
  description:
    'Terms of Use for the Rapidly platform. Read the rules and restrictions that govern your use of our services.',
  openGraph: {
    siteName: 'Rapidly',
    type: 'website',
    images: [{ url: CONFIG.OG_IMAGE_URL, width: 1200, height: 630 }],
  },
}

const sections = [
  {
    title: '1. Agreement & Eligibility',
    content: `These Terms of Use (the "Terms") are a binding contract between you and <strong>RAPIDLY SOFTWARE LTD.</strong> ("Rapidly," "we," "us," or "our"). By accessing or using our website(s), APIs, applications, or any related services (collectively, the "Services"), you agree to be bound by these Terms, our <a href="/legal/privacy" class="underline">Privacy Policy</a>, and any Additional Terms referenced herein.<br/><br/><strong>Eligibility.</strong> You must be at least 16 years of age and legally capable of entering into binding contracts to use the Services. If you are using the Services on behalf of a workspace, company, or other legal entity, you represent and warrant that you have authority to bind that entity to these Terms.<br/><br/><strong>Export Controls.</strong> You represent that you are not located in a country subject to a U.S. Government embargo, or listed on any U.S. Government list of prohibited or restricted parties. You agree to comply with all applicable export control laws and regulations in your use of the Services.`,
  },
  {
    title: '2. Changes to these Terms',
    content: `We may modify these Terms at any time. If we make material changes, we will notify you by email and/or by posting a notice on our website at least 30 days before the changes take effect. Your continued use of the Services after the effective date of updated Terms constitutes your acceptance. If you do not agree to the updated Terms, you must stop using the Services before they take effect.<br/><br/>No other amendment or modification of these Terms will be effective unless in writing and signed by both you and us.`,
  },
  {
    title: '3. Description of the Services',
    content: `Rapidly is a platform for secure file sharing, digital content distribution, and paid content management. The Services include, but are not limited to:<br/><br/><ul class="list-disc pl-6 space-y-1"><li><strong>Peer-to-Peer File Sharing:</strong> Encrypted, browser-based file transfers using WebRTC with AES-256-GCM encryption. Files transfer directly between devices; our servers facilitate the signaling connection but do not store or access your file contents.</li><li><strong>Secret Messages:</strong> Encrypted one-time messages and files that are automatically destroyed after a single retrieval, using client-side OpenPGP encryption.</li><li><strong>Payment Processing:</strong> Integration with third-party payment processors (currently Stripe, Inc.) to facilitate transactions.</li><li><strong>Workspaces &amp; Team Collaboration:</strong> Multi-user workspaces for teams to manage files, customers, analytics, and billing together.</li><li><strong>Customer Management:</strong> CRM-like tools for managing customers, portals, and member relationships.</li><li><strong>Analytics &amp; Events:</strong> Usage metrics, event tracking, revenue analytics, and real-time dashboards.</li><li><strong>Webhooks &amp; API Access:</strong> Programmatic access to platform data and real-time event notifications.</li><li><strong>Content Scanning:</strong> Automated malware and virus scanning of uploaded files using industry-standard scanning tools.</li></ul>`,
  },
  {
    title: '4. Account Terms',
    content: `<strong>Registration.</strong> You must provide accurate, complete, and current registration information. You may not use another person's name or identity without authorization, and you may not transfer your account without our prior written permission.<br/><br/><strong>Third-Party Accounts.</strong> You may authenticate using third-party services (GitHub, Google, Apple, Microsoft, Discord). By doing so, you authorize us to access certain information from your third-party account as permitted by your privacy settings on that service.<br/><br/><strong>Account Security.</strong> You are responsible for maintaining the confidentiality of your account credentials, including passwords, API tokens, and workspace access tokens. You are responsible for all activity that occurs under your account. Notify us immediately at <a href="mailto:support@rapidly.tech" class="underline">support@rapidly.tech</a> if you suspect unauthorized access.<br/><br/><strong>Workspace Accounts.</strong> If you create or join a workspace, the workspace administrator controls access, permissions, and data within that workspace. If your access is revoked by an administrator, you may lose access to data associated with that workspace. The workspace owner is responsible for ensuring compliance with these Terms for all workspace members.<br/><br/><strong>Inactive Accounts.</strong> We reserve the right to deactivate or delete accounts that have been inactive for 12 months or more, after providing reasonable notice to the email address on file.`,
  },
  {
    title: '5. Acceptable Use Policy',
    content: `You agree not to use the Services to upload, share, transmit, or otherwise make available any content or material ("Content") that:<br/><br/><ol class="list-decimal pl-6 space-y-1"><li>Is illegal, or promotes illegal activities, under applicable law;</li><li>Contains child sexual abuse material (CSAM) or exploits minors in any way;</li><li>Contains malware, viruses, trojans, worms, or other harmful code (note: all uploaded files are scanned for malware);</li><li>Infringes or violates the intellectual property, privacy, publicity, or other rights of any third party;</li><li>Is fraudulent, deceptive, misleading, or impersonates any person or entity;</li><li>Contains threats, harassment, hate speech, discrimination, or incitement to violence;</li><li>Is obscene, defamatory, or constitutes non-consensual intimate imagery;</li><li>Violates any applicable export control, sanctions, or trade compliance laws;</li><li>Constitutes or facilitates phishing, spam, or unsolicited commercial communications;</li><li>Attempts to gain unauthorized access to the Services, other accounts, computer systems, or networks;</li><li>Interferes with or disrupts the Services, servers, or networks, including through DDoS attacks or excessive automated requests;</li><li>"Crawls," "scrapes," or "spiders" any portion of the Services without written permission;</li><li>Circumvents any security measures, rate limits, access controls, or payment systems;</li><li>Decompiles, reverse engineers, or attempts to derive the source code of the Services (except as permitted by applicable law); or</li><li>Violates any other policy published by Rapidly, including our content guidelines.</li></ol><br/>Violation of this Acceptable Use Policy is grounds for immediate suspension or termination of your account.`,
  },
  {
    title: '6. Peer-to-Peer File Sharing & Encryption',
    content: `<strong>How It Works.</strong> Our file sharing service uses WebRTC to create direct, peer-to-peer connections between browsers. Files are encrypted with AES-256-GCM on your device before transmission. Rapidly's servers handle connection signaling but do not store, access, or decrypt your files.<br/><br/><strong>IP Address Disclosure.</strong> When using peer-to-peer file sharing, your IP address may be visible to the other party in the connection. This is an inherent characteristic of WebRTC. We hash and store IP addresses for abuse prevention purposes only.<br/><br/><strong>Download Quotas &amp; Expiration.</strong> Sharing channels may have configurable download limits and expiration times. Expired channels and their associated metadata are automatically deleted. File share links are not guaranteed to remain active indefinitely.<br/><br/><strong>Password Protection.</strong> You may set a password on sharing channels. Rapidly enforces server-side rate limiting on password attempts to prevent brute-force attacks. You are responsible for communicating passwords to intended recipients through a secure channel.<br/><br/><strong>Secret Messages &amp; Files.</strong> One-time secrets are encrypted with OpenPGP on your device and stored temporarily on our servers. They are permanently deleted after a single retrieval or upon expiration. Rapidly does not have access to the encryption key and cannot recover deleted secrets.<br/><br/><strong>Content Scanning.</strong> To protect our users and the platform, uploaded files may be scanned for malware and viruses. Files identified as malicious may be quarantined or deleted without notice. We do not scan the encrypted content of peer-to-peer transfers.<br/><br/><strong>Reporting &amp; Moderation.</strong> Users can report sharing channels for policy violations. Reported channels may be suspended pending review. Rapidly reserves the right to terminate any sharing channel that violates these Terms.`,
  },
  {
    title: '7. Payment Terms',
    content: `<strong>Payment Processing.</strong> All payment transactions are processed through our third-party Payment Processor, currently Stripe, Inc. By using paid features of the Services, you agree to Stripe's <a href="https://stripe.com/legal" class="underline" target="_blank" rel="noopener noreferrer">Terms of Service</a> and <a href="https://stripe.com/privacy" class="underline" target="_blank" rel="noopener noreferrer">Privacy Policy</a>. You authorize Rapidly and Stripe to charge your chosen payment method for all applicable fees.<br/><br/><strong>Platform Fees.</strong> Rapidly charges a platform fee on transactions processed through the Services. Current fee amounts are displayed at checkout and on our pricing page. We reserve the right to change fee structures with 30 days' prior notice.<br/><br/><strong>Refunds.</strong> Refund requests may be submitted by contacting <a href="mailto:support@rapidly.tech" class="underline">support@rapidly.tech</a>. Rapidly may, at its discretion, issue refunds in cases of service issues, non-delivery, or other qualifying circumstances. Refund eligibility and timelines are determined on a case-by-case basis.<br/><br/><strong>Taxes.</strong> You are solely responsible for determining and fulfilling your tax obligations, including collection and remittance of sales tax, VAT, GST, or other applicable taxes. Rapidly does not provide tax advice and is not responsible for your tax compliance.<br/><br/><strong>Currency.</strong> Transactions are processed in the currency specified at checkout. Exchange rates are determined by the Payment Processor.`,
  },
  {
    title: '8. Intellectual Property & Copyright',
    content: `<strong>Platform Ownership.</strong> The Services, including all software, design, text, graphics, and other materials (excluding User Content), are owned by Rapidly and protected by copyright, trademark, and other intellectual property laws. You may not copy, modify, distribute, or create derivative works based on the Services without our express written permission.<br/><br/><strong>User Content Ownership.</strong> You retain all intellectual property rights in the Content you upload or share through the Services. By using the Services, you grant Rapidly a non-exclusive, worldwide, royalty-free license to host, store, transmit, display, and distribute your Content solely as necessary to provide the Services. This license covers share descriptions, media attachments, profile content, and other materials hosted on the platform.<br/><br/><strong>Open Source.</strong> Certain components of the Services may be licensed under open source licenses (e.g., Apache 2.0). Where applicable, the terms of those licenses govern your use of those components.<br/><br/><strong>No Server-Side File Storage.</strong> Rapidly does not store the contents of files transferred via peer-to-peer sharing on its servers. Encrypted secret messages and files are stored temporarily and automatically deleted upon retrieval or expiration. However, Rapidly does host media attachments, profile content, and other user-submitted materials.<br/><br/><strong>Copyright Complaints.</strong> If you believe that material hosted on the Services (such as a media attachment or user-submitted material) infringes your copyright, please contact us at <a href="mailto:support@rapidly.tech" class="underline">support@rapidly.tech</a> with a description of the copyrighted work, the location of the allegedly infringing material, and your contact information. We will investigate and take appropriate action, which may include removal of the material.<br/><br/><strong>Repeat Infringers.</strong> Rapidly will terminate the accounts of users who repeatedly post infringing content on the platform.`,
  },
  {
    title: '9. Webhooks, API & Developer Terms',
    content: `<strong>API Access.</strong> We may provide API access and workspace access tokens for programmatic interaction with the Services. API access is subject to these Terms and any additional API documentation we publish.<br/><br/><strong>Rate Limits.</strong> We enforce rate limits on all API endpoints. Exceeding rate limits may result in temporary or permanent restriction of API access.<br/><br/><strong>API Token Security.</strong> You are responsible for securing your API tokens. Do not share tokens publicly or embed them in client-side code. Compromised tokens should be rotated immediately.<br/><br/><strong>Webhooks.</strong> If you configure webhook endpoints to receive event notifications, you are responsible for the security of your webhook endpoints and the proper handling of any data received. Rapidly is not responsible for data exposure resulting from misconfigured or insecure webhook endpoints.<br/><br/><strong>Restrictions.</strong> You may not use the API to: build a competing product or service, exceed reasonable usage limits, circumvent platform controls, or resell API access without written permission.`,
  },
  {
    title: '10. Privacy & Data Protection',
    content: `Rapidly takes the privacy of its users seriously. Our collection, use, and sharing of personal data is governed by our <a href="/legal/privacy" class="underline">Privacy Policy</a>, which is incorporated into these Terms by reference.<br/><br/><strong>Children's Privacy.</strong> The Services are not directed to children under 16 years of age. We do not knowingly collect personal information from children under 16. If we learn that we have collected personal information from a child under 16, we will delete that information as quickly as possible. If you believe a child under 16 has provided us with personal information, please contact us at <a href="mailto:support@rapidly.tech" class="underline">support@rapidly.tech</a>.<br/><br/><strong>Data Processing.</strong> If you are a workspace administrator processing personal data of your customers or team members through the Services, you are the data controller for that data. A Data Processing Agreement (DPA) is available upon request for qualifying business accounts by contacting <a href="mailto:data@rapidly.tech" class="underline">data@rapidly.tech</a>.`,
  },
  {
    title: '11. Communications',
    content: `As part of the Services, you may receive communications including transactional emails, security alerts, product updates, and marketing messages. You can manage your communication preferences in your dashboard settings. Note that certain communications (security alerts, Terms updates, account notifications) cannot be opted out of while you maintain an active account.<br/><br/>By agreeing to these Terms, you consent to receive electronic communications from us, and you agree that such electronic communications satisfy any legal requirement that such communications be in writing.`,
  },
  {
    title: '12. Account Suspension & Termination',
    content: `<strong>By You.</strong> You may terminate your account at any time by contacting <a href="mailto:support@rapidly.tech" class="underline">support@rapidly.tech</a> or through your account settings. Before termination, you should export any data you wish to retain. Active subscriptions should be cancelled before account deletion to avoid further charges.<br/><br/><strong>By Rapidly.</strong> We may suspend or terminate your access to the Services at any time, with or without cause, including for: violation of these Terms, suspected fraud or illegal activity, prolonged inactivity, non-payment, or upon request by law enforcement. Where practicable, we will provide advance notice before termination.<br/><br/><strong>Effects of Termination.</strong> Upon termination: (a) your right to access the Services ceases immediately; (b) Content associated with your account may be deleted after 30 days; (c) you remain liable for any outstanding fees or obligations.<br/><br/><strong>Re-registration.</strong> Users whose accounts have been terminated for policy violations may not create new accounts without written permission from Rapidly.<br/><br/><strong>Survival.</strong> Sections related to intellectual property, indemnification, limitation of liability, dispute resolution, and any accrued payment obligations survive termination.`,
  },
  {
    title: '13. Service Availability & Modifications',
    content: `We strive to maintain high availability of the Services but do not guarantee uninterrupted access. We may modify, suspend, or discontinue any part of the Services at any time. We will provide reasonable notice before discontinuing material features.<br/><br/>We reserve the right to remove any Content from the Services at any time if we believe it violates these Terms, applicable law, or poses a risk to the platform or other users.<br/><br/><strong>Beta Features.</strong> We may offer beta or experimental features. These are provided "as-is" without warranty and may be modified or discontinued without notice.`,
  },
  {
    title: '14. Referrals',
    content: `From time to time Rapidly may offer rewards or incentives for referring new users. Referrals are subject to the following rules: (a) referees must be new to Rapidly; (b) multiple referrals to the same person or entity will be disregarded; (c) Rapidly reserves the right to modify or terminate referral programs at any time; (d) abuse of referral programs, including self-referrals or fraudulent referrals, may result in revocation of rewards and account suspension.`,
  },
  {
    title: '15. Disclaimer of Warranties',
    content: `<strong>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW,</strong> the Services and all Content are provided "as is" and "as available" without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement.<br/><br/>Rapidly does not warrant that: (a) the Services will be uninterrupted, timely, secure, or error-free; (b) Content transmitted through the Services will be accurate or reliable; (c) defects will be corrected; or (d) the Services or servers are free of viruses or other harmful components.<br/><br/>You acknowledge that peer-to-peer file transfers rely on network conditions outside of Rapidly's control, and transfer speeds or success are not guaranteed. You further acknowledge that encryption does not eliminate all risk of unauthorized access.<br/><br/><strong>EU Consumer Rights.</strong> If you are a consumer in the EEA or UK, this disclaimer does not affect your statutory rights under the EU Digital Content Directive (2019/770), the Irish Consumer Rights Act 2022, or equivalent consumer protection laws in your country of residence. You retain all statutory rights regarding the conformity of digital services, including the right to have non-conforming services brought into conformity or to receive an appropriate price reduction. These statutory rights cannot be excluded or limited by contract.`,
  },
  {
    title: '16. Limitation of Liability',
    content: `<strong>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW,</strong> in no event shall Rapidly or its officers, directors, employees, agents, affiliates, successors, or assigns (the "Rapidly Parties") be liable for:<br/><br/><strong>(A)</strong> Any indirect, special, incidental, punitive, or consequential damages of any kind, including damages for lost profits, lost data, business interruption, loss of goodwill, or computer failure, regardless of the legal theory;<br/><br/><strong>(B)</strong> Any substitute goods, services, or technology;<br/><br/><strong>(C)</strong> Any amount, in the aggregate, exceeding the greater of (i) five hundred euros (€500) or (ii) the total amounts paid by you to Rapidly in the twelve (12) months preceding the claim; or<br/><br/><strong>(D)</strong> Any matter beyond our reasonable control.<br/><br/><strong>Exceptions — The above limitations do NOT apply to:</strong><ul class="list-disc pl-6 space-y-1 mt-2"><li>Liability for death or personal injury caused by negligence;</li><li>Liability for fraud or fraudulent misrepresentation;</li><li>Liability for gross negligence or willful misconduct;</li><li>Rapidly's obligations under applicable data protection law (including GDPR);</li><li>Any liability which cannot be excluded or limited under applicable law, including mandatory consumer protection rights under the Irish Consumer Rights Act 2022, the EU Digital Content Directive (2019/770), or equivalent legislation in your country of residence.</li></ul><br/><strong>Nothing in these Terms excludes or limits any liability which cannot be excluded or limited under applicable law.</strong> If you are a consumer in the EEA or UK, your statutory rights remain unaffected.`,
  },
  {
    title: '17. Indemnification',
    content: `You agree to indemnify, defend, and hold harmless the Rapidly Parties from and against any and all claims, liabilities, damages, losses, and expenses (including reasonable attorneys' fees) arising from or relating to: (a) your use of the Services; (b) your violation of these Terms; (c) your violation of any third-party rights, including intellectual property, privacy, or publicity rights; (d) Content you upload or share through the Services; or (e) your violation of any applicable law or regulation.`,
  },
  {
    title: '18. Dispute Resolution & Governing Law',
    content: `<strong>Informal Resolution.</strong> Before initiating formal dispute resolution, you agree to contact us at <a href="mailto:support@rapidly.tech" class="underline">support@rapidly.tech</a> and attempt to resolve the dispute informally for at least 30 days.<br/><br/><strong>Governing Law.</strong> These Terms are governed by and construed in accordance with the laws of Ireland. If you are a consumer resident in the European Economic Area (EEA), United Kingdom, or Switzerland, you will benefit from any mandatory provisions of the law of the country in which you are resident. Nothing in these Terms, including this choice of law provision, affects your rights as a consumer to rely on such mandatory provisions of local law.<br/><br/><strong>Jurisdiction.</strong> Any dispute arising out of or relating to these Terms or the Services that cannot be resolved informally shall be submitted to the jurisdiction of the courts of Ireland. If you are a consumer in the EU, you may also bring proceedings in the courts of the EU member state in which you reside, and we will bring proceedings against you only in the courts of your country of residence.<br/><br/><strong>EU Online Dispute Resolution.</strong> If you are a consumer in the European Union, you may use the European Commission's Online Dispute Resolution platform at <a href="https://ec.europa.eu/consumers/odr" class="underline" target="_blank" rel="noopener noreferrer">ec.europa.eu/consumers/odr</a>.`,
  },
  {
    title: '19. Force Majeure',
    content: `Neither party shall be liable for any failure or delay in performing obligations under these Terms caused by events beyond reasonable control, including but not limited to: acts of God, natural disasters, pandemics, epidemics, wars, terrorism, civil unrest, labor disputes, government actions, sanctions, embargoes, internet or telecommunications failures, power outages, cyberattacks, or third-party service provider failures. If a force majeure event continues for more than 60 days, either party may terminate the affected Services upon written notice.`,
  },
  {
    title: '20. General Provisions',
    content: `<strong>Assignment.</strong> You may not assign or transfer these Terms or your rights hereunder without Rapidly's prior written consent. Rapidly may assign these Terms in connection with a merger, acquisition, or sale of assets.<br/><br/><strong>Severability.</strong> If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary, and the remaining provisions shall remain in full force and effect.<br/><br/><strong>Entire Agreement.</strong> These Terms, together with the Privacy Policy and any Additional Terms, constitute the entire agreement between you and Rapidly regarding the Services and supersede all prior agreements and understandings.<br/><br/><strong>No Waiver.</strong> Our failure to enforce any right or provision of these Terms shall not be deemed a waiver of that right or provision.<br/><br/><strong>Notices.</strong> We may send notices to you via email, through the Services, or by posting on our website. Notices to Rapidly should be sent to <a href="mailto:legal@rapidly.tech" class="underline">legal@rapidly.tech</a>.<br/><br/><strong>Third-Party Beneficiaries.</strong> Except as expressly stated in the arbitration section, there are no third-party beneficiaries to these Terms.<br/><br/><strong>Feedback.</strong> Any feedback, suggestions, or ideas you provide to Rapidly about the Services may be used by us without obligation or compensation to you.<br/><br/><strong>Electronic Communications.</strong> You agree that communications from us satisfy any legal requirement that such communications be in writing.`,
  },
  {
    title: '21. Contact Us',
    content: `If you have any questions about these Terms, please contact us at:<br/><br/><strong>Rapidly Software Ltd.</strong><br/>Cork, Ireland<br/><br/>Email: <a href="mailto:legal@rapidly.tech" class="underline">legal@rapidly.tech</a><br/>Support: <a href="mailto:support@rapidly.tech" class="underline">support@rapidly.tech</a>`,
  },
]

export default function TermsPage() {
  return (
    <LegalPage
      icon="Scale"
      title="Terms of Use"
      effectiveDate="April 2, 2026"
      intro="Welcome to Rapidly. These Terms of Use govern your access to and use of the Rapidly platform, including our website, applications, APIs, and all related services. Please read them carefully. By using the Services, you agree to be bound by these Terms, our Privacy Policy, and any additional terms referenced herein. If you do not agree, do not use the Services."
      sections={sections}
    />
  )
}
