"""Per-step record within an agent Run.

Each call into a node by the execution engine (M4.2) creates a
NodeRun row at start and updates it on completion. NodeRuns are
the unit of audit + the unit of trace-event correlation — every
event in ``analytics/eventstream`` tagged with ``node_run_id``
points back here.

Status semantics:
    pending          — queued, engine hasn't dispatched yet
    running          — handler is executing
    succeeded        — output_data populated
    failed           — error_message populated
    skipped          — a branch's input condition routed past this
                       node, or the engine decided to skip it for
                       another reason (e.g. cancelled run)
    awaiting_human   — human-in-the-loop node parked

Immutable from the API's perspective: clients list + get, never
edit. The engine is the only writer.

``parent_node_run_id`` is a self-FK that distinguishes loop
iterations + branch arms. A Loop node's body runs N times, each
iteration getting its own NodeRun row with parent_node_run_id
pointing at the Loop's NodeRun. Same pattern for the Branch node
+ sub-workflow node — the parent chain is what the UI walks to
render the tree view of a complex run.
"""

from datetime import datetime
from enum import StrEnum
from typing import TYPE_CHECKING, Any
from uuid import UUID

from sqlalchemy import TIMESTAMP, ForeignKey, String, Text, Uuid
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, declared_attr, mapped_column, relationship

from rapidly.core.db.models import BaseEntity
from rapidly.core.extensions.sqlalchemy import StringEnum

if TYPE_CHECKING:
    from .agent_run import Run


class NodeRunStatus(StrEnum):
    pending = "pending"
    running = "running"
    succeeded = "succeeded"
    failed = "failed"
    skipped = "skipped"
    awaiting_human = "awaiting_human"


# Terminal node-run states. ``skipped`` is terminal because once a
# branch routes past a node, the engine won't revisit it within
# the same Run.
TERMINAL_NODE_RUN_STATUSES: frozenset[NodeRunStatus] = frozenset(
    {
        NodeRunStatus.succeeded,
        NodeRunStatus.failed,
        NodeRunStatus.skipped,
    }
)


class NodeRun(BaseEntity):
    """A single node execution within a Run."""

    __tablename__ = "agent_node_runs"

    run_id: Mapped[UUID] = mapped_column(
        Uuid,
        ForeignKey("agent_runs.id", ondelete="cascade"),
        nullable=False,
        index=True,
    )

    # Graph-local id from the WorkflowVersion.graph_json. Short
    # string (ulid-like) generated by the editor; not a UUID column
    # so the runtime can hop between version snapshots without
    # rewriting node ids on every publish.
    node_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    node_type: Mapped[str] = mapped_column(String(64), nullable=False)

    status: Mapped[NodeRunStatus] = mapped_column(
        StringEnum(NodeRunStatus, length=16),
        nullable=False,
        default=NodeRunStatus.pending,
    )

    started_at: Mapped[datetime | None] = mapped_column(
        TIMESTAMP(timezone=True), nullable=True
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        TIMESTAMP(timezone=True), nullable=True
    )
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    input_data: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict
    )
    output_data: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict
    )

    # Self-FK for loop iterations + branch arms + sub-workflow
    # parents. NULL on top-level node runs.
    parent_node_run_id: Mapped[UUID | None] = mapped_column(
        Uuid,
        ForeignKey("agent_node_runs.id", ondelete="cascade"),
        nullable=True,
        index=True,
    )

    @declared_attr
    def run(cls) -> Mapped["Run"]:
        return relationship("Run", lazy="raise")
