"""Pending invitation for a user to join a project.

Mirrors Plane's ``ProjectMemberInvite``.  An admin issues an invite
to an existing workspace member (the invitee); the invitee accepts
to turn the invite into a ``ProjectMember`` row.  No external-email
flow yet — invitees must already be workspace members.

Invariants:

- ``token`` is a secure random nonce; the invitee accepts the invite
  by presenting it.  The token is generated by the action layer and
  never recycled across rows.
- A pending invite blocks duplicate invitations to the same user;
  once accepted/declined/revoked, ``accepted_at`` / ``declined_at`` /
  ``revoked_at`` is set and a new invite for the same target is OK.
"""

from datetime import datetime
from enum import StrEnum
from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import (
    TIMESTAMP,
    ForeignKey,
    Index,
    String,
    UniqueConstraint,
    Uuid,
)
from sqlalchemy.orm import Mapped, declared_attr, mapped_column, relationship

from rapidly.core.db.models import BaseEntity
from rapidly.core.extensions.sqlalchemy import StringEnum

if TYPE_CHECKING:
    from .project import Project
    from .project_member import ProjectMemberRole
    from .user import User


# Reuse the role enum from project_member but as a string-typed column
# to avoid a circular import at table-definition time.  The action
# layer validates membership of ``ProjectMemberRole`` before insert.


class ProjectMemberInviteStatus(StrEnum):
    """Lifecycle state for a project-member invite."""

    pending = "pending"
    accepted = "accepted"
    declined = "declined"
    revoked = "revoked"


class ProjectMemberInvite(BaseEntity):
    """An invitation for a user to join a project."""

    __tablename__ = "project_member_invites"
    __table_args__ = (
        # A token is the secret; uniqueness lets us look it up O(1) and
        # rejects accidental reuse if random-generation ever collides.
        UniqueConstraint("token", name="project_member_invites_token_key"),
        # Speeds up "show me my pending invites" — the most common
        # invitee-side query.
        Index(
            "ix_project_member_invites_invitee_status",
            "invitee_id",
            "status",
        ),
    )

    project_id: Mapped[UUID] = mapped_column(
        Uuid,
        ForeignKey("projects.id", ondelete="cascade"),
        nullable=False,
        index=True,
    )
    invitee_id: Mapped[UUID] = mapped_column(
        Uuid,
        ForeignKey("users.id", ondelete="cascade"),
        nullable=False,
        index=True,
    )
    invited_by_id: Mapped[UUID | None] = mapped_column(
        Uuid,
        ForeignKey("users.id", ondelete="set null"),
        nullable=True,
        index=True,
    )

    # Stored as the literal enum value of ProjectMemberRole — kept as
    # a String column (not StringEnum) to avoid a circular FK at model
    # registration time.  Validated in actions.create.
    role: Mapped[str] = mapped_column(String(16), nullable=False)

    token: Mapped[str] = mapped_column(String(64), nullable=False)

    status: Mapped[ProjectMemberInviteStatus] = mapped_column(
        StringEnum(ProjectMemberInviteStatus, length=16),
        nullable=False,
        default=ProjectMemberInviteStatus.pending,
    )

    accepted_at: Mapped[datetime | None] = mapped_column(
        TIMESTAMP(timezone=True), nullable=True
    )
    declined_at: Mapped[datetime | None] = mapped_column(
        TIMESTAMP(timezone=True), nullable=True
    )
    revoked_at: Mapped[datetime | None] = mapped_column(
        TIMESTAMP(timezone=True), nullable=True
    )

    @declared_attr
    def project(cls) -> Mapped["Project"]:
        return relationship("Project", lazy="raise")

    @declared_attr
    def invitee(cls) -> Mapped["User"]:
        # Two FKs to ``users`` (invitee_id + invited_by_id) means
        # SQLAlchemy can't auto-discover which to use — string form
        # avoids mypy's column-vs-FK-instrumented-attribute confusion.
        return relationship(
            "User", lazy="raise", foreign_keys="ProjectMemberInvite.invitee_id"
        )

    @declared_attr
    def invited_by(cls) -> Mapped["User | None"]:
        return relationship(
            "User",
            lazy="raise",
            foreign_keys="ProjectMemberInvite.invited_by_id",
        )

    @property
    def role_enum(self) -> "ProjectMemberRole":
        """Decode the string-stored role back to its enum form."""
        from .project_member import ProjectMemberRole as Role

        return Role(self.role)
