"""Word list for generating human-readable slugs.

With 128 words and 7-word slugs: 128^7 ~= 5.6 * 10^14 (~49 bits of entropy).
At 60 requests/IP/min rate limit, brute-force would take ~178 million years.

The list MUST contain exactly 128 words — any change affects entropy calculations.
"""

TOPPINGS = [
    "alfalfa",
    "almonds",
    "anchovies",
    "artichoke",
    "avocado",
    "bacon",
    "basil",
    "bayleaves",
    "bbqchicken",
    "beans",
    "beef",
    "beetroot",
    "bluecheese",
    "brie",
    "broccoli",
    "cajunchicken",
    "camembert",
    "capers",
    "capicolla",
    "cardamon",
    "carrot",
    "cauliflower",
    "cheddar",
    "chickenmasala",
    "chickentikka",
    "chili",
    "chives",
    "chorizo",
    "cilantro",
    "colby",
    "coriander",
    "crayfish",
    "cumin",
    "dill",
    "duck",
    "eggplant",
    "fenugreek",
    "feta",
    "fungi",
    "garlic",
    "goatcheese",
    "gorgonzola",
    "gouda",
    "ham",
    "jalapeno",
    "laurel",
    "leeks",
    "lettuce",
    "limburger",
    "lobster",
    "manchego",
    "marjoram",
    "meatballs",
    "melon",
    "montereyjack",
    "mozzarella",
    "muenster",
    "mushrooms",
    "olives",
    "onion",
    "oregano",
    "oysters",
    "parsley",
    "parmesan",
    "peanuts",
    "peas",
    "pecans",
    "pepperoni",
    "peppers",
    "pineapple",
    "pinenuts",
    "pistachios",
    "prawn",
    "prosciutto",
    "provolone",
    "ricotta",
    "romano",
    "roquefort",
    "rosemary",
    "salami",
    "salmon",
    "sausage",
    "scallions",
    "shallots",
    "shrimp",
    "snowpeas",
    "spinach",
    "squash",
    "squid",
    "sweetcorn",
    "tomatoes",
    "tuna",
    "turkey",
    "venison",
    "walnuts",
    "watercress",
    "whitebait",
    "zucchini",
    # Additional words for increased entropy (101 -> 128)
    "arugula",
    "asparagus",
    "bamboo",
    "cabbage",
    "cashews",
    "celery",
    "chestnut",
    "coconut",
    "cranberry",
    "edamame",
    "fennel",
    "ginger",
    "hazelnut",
    "horseradish",
    "kale",
    "lemongrass",
    "lentils",
    "mango",
    "nutmeg",
    "okra",
    "papaya",
    "paprika",
    "radish",
    "saffron",
    "tarragon",
    "thyme",
    "truffle",
    "turmeric",
    "turnip",
    "wasabi",
]

if len(TOPPINGS) != 128:
    raise ValueError(f"TOPPINGS must contain exactly 128 words, got {len(TOPPINGS)}")
if len(set(TOPPINGS)) != 128:
    raise ValueError(
        "TOPPINGS contains duplicate words — each word must be unique for full entropy"
    )
