#!/usr/bin/env python3
"""
Setup script for event ingestion load tests.

Creates test customers and meters in an existing workspace,
then outputs environment variables for the load test.

Usage:
    uv run python scripts/loadtest_setup.py --workspace-slug coldmail --num-customers 20
    uv run python scripts/loadtest_setup.py -o coldmail -n 20 -f .env.loadtest
"""

import asyncio
import os
from datetime import datetime

import dramatiq
import typer

import rapidly.workers  # noqa: F401 - Import jobs to register all dramatiq actors
from rapidly.core.db.postgres import create_async_sessionmaker
from rapidly.customers.customer import actions as customer_service
from rapidly.customers.customer.types.customer import CustomerCreate
from rapidly.identity.auth.models import AuthPrincipal
from rapidly.platform.workspace.queries import WorkspaceRepository
from rapidly.platform.workspace_membership import (
    actions as workspace_membership_service,
)
from rapidly.postgres import AsyncSession, create_async_engine
from rapidly.redis import create_redis
from rapidly.worker import JobQueueManager

cli = typer.Typer()


async def create_loadtest_data(
    session: AsyncSession,
    workspace_slug: str,
    num_customers: int,
    output_file: str | None,
) -> None:
    """Create load test data in the specified workspace."""
    # Get workspace
    org_repository = WorkspaceRepository.from_session(session)
    workspace = await org_repository.get_by_slug(workspace_slug)
    if workspace is None:
        typer.echo(f"Error: Workspace '{workspace_slug}' not found", err=True)
        raise typer.Exit(1)

    # Get workspace members for auth context
    members = await workspace_membership_service.list_by_workspace(
        session, workspace.id
    )
    if not members:
        typer.echo("Error: Workspace has no members", err=True)
        raise typer.Exit(1)

    admin_user = members[0].user
    auth_subject = AuthPrincipal(subject=admin_user, scopes=set(), session=None)

    typer.echo(
        f"Setting up load test data for workspace: {workspace.name}",
        err=True,
    )

    # Generate unique suffix for this run
    run_id = datetime.now().strftime("%Y%m%d%H%M%S")

    # Create customers with external IDs
    external_customer_ids = []
    for i in range(num_customers):
        external_id = f"loadtest-{run_id}-{i + 1}"
        customer = await customer_service.create(
            session=session,
            customer_create=CustomerCreate(
                email=f"{external_id}@rapidly.tech",
                name=f"Load Test Customer {i + 1}",
                external_id=external_id,
                workspace_id=workspace.id,
            ),
            auth_subject=auth_subject,
        )
        external_customer_ids.append(external_id)
        typer.echo(f"Created customer {i + 1}/{num_customers}", err=True)

    await session.commit()

    # Never write actual tokens to files — always use a placeholder.
    # The real token should be set via the LOAD_TEST_API_TOKEN env var at runtime.
    api_token_line = "LOAD_TEST_API_TOKEN=rapidly_oat_REPLACE_WITH_YOUR_TOKEN"
    existing_token = os.getenv("LOAD_TEST_API_TOKEN")

    # Output .env format
    env_output = f"""# Event Ingestion Load Test Configuration
# Generated by loadtest_setup.py
# Workspace: {workspace.name} ({workspace_slug})

# Required: API host and authentication
# Note: Use an workspace access token (rapidly_oat_*) for this workspace
LOAD_TEST_HOST=http://127.0.0.1:8000
{api_token_line}

# Event ingestion test data (external customer IDs)
LOAD_TEST_EVENT_EXTERNAL_CUSTOMER_IDS={",".join(external_customer_ids)}

# Optional: Batch size (default: 10)
# LOAD_TEST_EVENT_BATCH_SIZE=10
"""

    if output_file:
        fd = os.open(output_file, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w") as f:
            f.write(env_output)
        typer.echo(f"\nConfiguration written to {output_file}", err=True)
    else:
        typer.echo(env_output)

    typer.echo(f"\nCreated {num_customers} customers", err=True)
    if not existing_token:
        typer.echo(
            "⚠️  Remember to replace LOAD_TEST_API_TOKEN with your actual token!",
            err=True,
        )


@cli.command()
def setup(
    workspace_slug: str = typer.Option(
        ..., "--workspace-slug", "-o", help="Workspace slug"
    ),
    num_customers: int = typer.Option(
        20, "--num-customers", "-n", help="Number of customers to create"
    ),
    output: str | None = typer.Option(
        None, "--output", "-f", help="Output file path (default: stdout)"
    ),
) -> None:
    """Setup load test data for event ingestion."""

    async def run() -> None:
        redis = create_redis("app")
        async with JobQueueManager.open(dramatiq.get_broker(), redis):
            engine = create_async_engine("script")
            sessionmaker = create_async_sessionmaker(engine)
            async with sessionmaker() as session:
                await create_loadtest_data(
                    session, workspace_slug, num_customers, output
                )

    asyncio.run(run())


if __name__ == "__main__":
    cli()
