"""add recent_visits table

Revision ID: 3f343538f26b
Revises: 27ed2e68876f
Create Date: 2026-05-20 21:23:07.406112

"""

import sqlalchemy as sa
from alembic import op

# Rapidly Custom Imports
from rapidly.core.extensions.sqlalchemy.types import StringEnum
from rapidly.models.recent_visit import RecentVisitEntityType

# revision identifiers, used by Alembic.
revision = "3f343538f26b"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recent_visits",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "entity_type",
            StringEnum(RecentVisitEntityType, length=16),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("visited_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("recent_visits_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("recent_visits_workspace_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("recent_visits_pkey")),
        sa.UniqueConstraint(
            "user_id", "entity_type", "entity_id", name="recent_visits_user_entity_key"
        ),
    )
    op.create_index(
        op.f("ix_recent_visits_created_at"),
        "recent_visits",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recent_visits_deleted_at"),
        "recent_visits",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recent_visits_entity_id"), "recent_visits", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_recent_visits_user_id"), "recent_visits", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_recent_visits_visited_at"),
        "recent_visits",
        ["visited_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recent_visits_workspace_id"),
        "recent_visits",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recent_visits_workspace_id"), table_name="recent_visits")
    op.drop_index(op.f("ix_recent_visits_visited_at"), table_name="recent_visits")
    op.drop_index(op.f("ix_recent_visits_user_id"), table_name="recent_visits")
    op.drop_index(op.f("ix_recent_visits_entity_id"), table_name="recent_visits")
    op.drop_index(op.f("ix_recent_visits_deleted_at"), table_name="recent_visits")
    op.drop_index(op.f("ix_recent_visits_created_at"), table_name="recent_visits")
    op.drop_table("recent_visits")
    # ### end Alembic commands ###
