"""add_project_views_table

Revision ID: a44882363b19
Revises: 27ed2e68876f
Create Date: 2026-05-19 01:09:26.604858

"""

import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "a44882363b19"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_project_pages_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_pages",
        columns=[
            "access",
            "archived_at",
            "created_at",
            "deleted_at",
            "description_binary",
            "description_html",
            "description_json",
            "id",
            "is_locked",
            "modified_at",
            "name",
            "owner_id",
            "parent_id",
            "project_id",
            "slug",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_project_pages_rapidly_read_select)

    public_user_favorites_rapidly_read_select = PGGrantTable(
        schema="public",
        table="user_favorites",
        columns=[
            "created_at",
            "deleted_at",
            "entity_id",
            "entity_type",
            "id",
            "modified_at",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_user_favorites_rapidly_read_select)

    op.create_table(
        "project_views",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("archived_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("project_views_owner_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("project_views_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_views_pkey")),
        sa.UniqueConstraint(
            "project_id", "name", name="project_views_project_id_name_key"
        ),
    )
    op.create_index(
        op.f("ix_project_views_archived_at"),
        "project_views",
        ["archived_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_views_created_at"),
        "project_views",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_views_deleted_at"),
        "project_views",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_views_owner_id"), "project_views", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_views_project_id"),
        "project_views",
        ["project_id"],
        unique=False,
    )

    # The initial migration's ``ALTER DEFAULT PRIVILEGES`` grants
    # SELECT to ``rapidly_read`` on every new public-schema table.
    # No model registers a PGGrantTable for project_views, so
    # alembic_utils would see the grant as drift and propose
    # dropping it.  Drop here to keep ``alembic check`` clean.
    # (See ``feedback_ci_rapidly_read`` memory for the full story.)
    public_project_views_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_views",
        columns=[
            "archived_at",
            "created_at",
            "deleted_at",
            "description",
            "filters",
            "id",
            "modified_at",
            "name",
            "owner_id",
            "project_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_project_views_rapidly_read_select)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Symmetric counterpart to the upgrade's drop_entity — re-grant
    # SELECT to rapidly_read before dropping the table.
    public_project_views_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_views",
        columns=[
            "archived_at",
            "created_at",
            "deleted_at",
            "description",
            "filters",
            "id",
            "modified_at",
            "name",
            "owner_id",
            "project_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_project_views_rapidly_read_select)

    op.drop_index(op.f("ix_project_views_project_id"), table_name="project_views")
    op.drop_index(op.f("ix_project_views_owner_id"), table_name="project_views")
    op.drop_index(op.f("ix_project_views_deleted_at"), table_name="project_views")
    op.drop_index(op.f("ix_project_views_created_at"), table_name="project_views")
    op.drop_index(op.f("ix_project_views_archived_at"), table_name="project_views")
    op.drop_table("project_views")
    public_user_favorites_rapidly_read_select = PGGrantTable(
        schema="public",
        table="user_favorites",
        columns=[
            "created_at",
            "deleted_at",
            "entity_id",
            "entity_type",
            "id",
            "modified_at",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_user_favorites_rapidly_read_select)

    public_project_pages_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_pages",
        columns=[
            "access",
            "archived_at",
            "created_at",
            "deleted_at",
            "description_binary",
            "description_html",
            "description_json",
            "id",
            "is_locked",
            "modified_at",
            "name",
            "owner_id",
            "parent_id",
            "project_id",
            "slug",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_project_pages_rapidly_read_select)

    # ### end Alembic commands ###
