"""add project_member_invites table

Revision ID: b9f533b55e06
Revises: 27ed2e68876f
Create Date: 2026-05-20 19:43:31.780185

"""

import sqlalchemy as sa
from alembic import op

# Rapidly Custom Imports
from rapidly.core.extensions.sqlalchemy.types import StringEnum
from rapidly.models.project_member_invite import ProjectMemberInviteStatus

# revision identifiers, used by Alembic.
revision = "b9f533b55e06"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_member_invites",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("invitee_id", sa.Uuid(), nullable=False),
        sa.Column("invited_by_id", sa.Uuid(), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            StringEnum(ProjectMemberInviteStatus, length=16),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("declined_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["invited_by_id"],
            ["users.id"],
            name=op.f("project_member_invites_invited_by_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["invitee_id"],
            ["users.id"],
            name=op.f("project_member_invites_invitee_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("project_member_invites_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_member_invites_pkey")),
        sa.UniqueConstraint("token", name="project_member_invites_token_key"),
    )
    op.create_index(
        op.f("ix_project_member_invites_created_at"),
        "project_member_invites",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_member_invites_deleted_at"),
        "project_member_invites",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_member_invites_invited_by_id"),
        "project_member_invites",
        ["invited_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_member_invites_invitee_id"),
        "project_member_invites",
        ["invitee_id"],
        unique=False,
    )
    op.create_index(
        "ix_project_member_invites_invitee_status",
        "project_member_invites",
        ["invitee_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_member_invites_project_id"),
        "project_member_invites",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_member_invites_project_id"),
        table_name="project_member_invites",
    )
    op.drop_index(
        "ix_project_member_invites_invitee_status", table_name="project_member_invites"
    )
    op.drop_index(
        op.f("ix_project_member_invites_invitee_id"),
        table_name="project_member_invites",
    )
    op.drop_index(
        op.f("ix_project_member_invites_invited_by_id"),
        table_name="project_member_invites",
    )
    op.drop_index(
        op.f("ix_project_member_invites_deleted_at"),
        table_name="project_member_invites",
    )
    op.drop_index(
        op.f("ix_project_member_invites_created_at"),
        table_name="project_member_invites",
    )
    op.drop_table("project_member_invites")
    # ### end Alembic commands ###
