"""add project_cycle tables

Revision ID: db862b1bb5a5
Revises: 942c379a2580
Create Date: 2026-05-12 19:39:27.377466

"""

import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "db862b1bb5a5"
down_revision = "942c379a2580"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_work_item_comments_rapidly_read_select = PGGrantTable(
        schema="public",
        table="work_item_comments",
        columns=[
            "actor_id",
            "body_html",
            "body_json",
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "work_item_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_work_item_comments_rapidly_read_select)

    public_work_item_relations_rapidly_read_select = PGGrantTable(
        schema="public",
        table="work_item_relations",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "related_id",
            "relation_type",
            "work_item_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_work_item_relations_rapidly_read_select)

    op.create_table(
        "project_cycles",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("end_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("archived_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("project_cycles_owner_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("project_cycles_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_cycles_pkey")),
        sa.UniqueConstraint(
            "project_id", "name", name="project_cycles_project_id_name_key"
        ),
    )
    op.create_index(
        op.f("ix_project_cycles_archived_at"),
        "project_cycles",
        ["archived_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_cycles_created_at"),
        "project_cycles",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_cycles_deleted_at"),
        "project_cycles",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_cycles_owner_id"), "project_cycles", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_cycles_project_id"),
        "project_cycles",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "project_cycle_work_items",
        sa.Column("cycle_id", sa.Uuid(), nullable=False),
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["project_cycles.id"],
            name=op.f("project_cycle_work_items_cycle_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("project_cycle_work_items_work_item_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_cycle_work_items_pkey")),
        sa.UniqueConstraint(
            "cycle_id",
            "work_item_id",
            name="project_cycle_work_items_cycle_id_work_item_id_key",
        ),
    )
    op.create_index(
        op.f("ix_project_cycle_work_items_created_at"),
        "project_cycle_work_items",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_cycle_work_items_cycle_id"),
        "project_cycle_work_items",
        ["cycle_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_cycle_work_items_deleted_at"),
        "project_cycle_work_items",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_cycle_work_items_work_item_id"),
        "project_cycle_work_items",
        ["work_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_cycle_work_items_work_item_id"),
        table_name="project_cycle_work_items",
    )
    op.drop_index(
        op.f("ix_project_cycle_work_items_deleted_at"),
        table_name="project_cycle_work_items",
    )
    op.drop_index(
        op.f("ix_project_cycle_work_items_cycle_id"),
        table_name="project_cycle_work_items",
    )
    op.drop_index(
        op.f("ix_project_cycle_work_items_created_at"),
        table_name="project_cycle_work_items",
    )
    op.drop_table("project_cycle_work_items")
    op.drop_index(op.f("ix_project_cycles_project_id"), table_name="project_cycles")
    op.drop_index(op.f("ix_project_cycles_owner_id"), table_name="project_cycles")
    op.drop_index(op.f("ix_project_cycles_deleted_at"), table_name="project_cycles")
    op.drop_index(op.f("ix_project_cycles_created_at"), table_name="project_cycles")
    op.drop_index(op.f("ix_project_cycles_archived_at"), table_name="project_cycles")
    op.drop_table("project_cycles")
    public_work_item_relations_rapidly_read_select = PGGrantTable(
        schema="public",
        table="work_item_relations",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "related_id",
            "relation_type",
            "work_item_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_work_item_relations_rapidly_read_select)

    public_work_item_comments_rapidly_read_select = PGGrantTable(
        schema="public",
        table="work_item_comments",
        columns=[
            "actor_id",
            "body_html",
            "body_json",
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "work_item_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_work_item_comments_rapidly_read_select)

    # ### end Alembic commands ###
