"""add work_item_mentions table

Revision ID: dde8a9cfdc2b
Revises: 27ed2e68876f
Create Date: 2026-05-20 20:36:32.527195

"""

import sqlalchemy as sa
from alembic import op

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "dde8a9cfdc2b"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_item_mentions",
        sa.Column("comment_id", sa.Uuid(), nullable=False),
        sa.Column("mentioned_user_id", sa.Uuid(), nullable=False),
        sa.Column("mentioned_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["work_item_comments.id"],
            name=op.f("work_item_mentions_comment_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["mentioned_by_id"],
            ["users.id"],
            name=op.f("work_item_mentions_mentioned_by_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["mentioned_user_id"],
            ["users.id"],
            name=op.f("work_item_mentions_mentioned_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("work_item_mentions_pkey")),
        sa.UniqueConstraint(
            "comment_id",
            "mentioned_user_id",
            name="work_item_mentions_comment_id_mentioned_user_id_key",
        ),
    )
    op.create_index(
        op.f("ix_work_item_mentions_comment_id"),
        "work_item_mentions",
        ["comment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_mentions_created_at"),
        "work_item_mentions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_mentions_deleted_at"),
        "work_item_mentions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_mentions_mentioned_by_id"),
        "work_item_mentions",
        ["mentioned_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_mentions_mentioned_user_id"),
        "work_item_mentions",
        ["mentioned_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_work_item_mentions_mentioned_user_id"), table_name="work_item_mentions"
    )
    op.drop_index(
        op.f("ix_work_item_mentions_mentioned_by_id"), table_name="work_item_mentions"
    )
    op.drop_index(
        op.f("ix_work_item_mentions_deleted_at"), table_name="work_item_mentions"
    )
    op.drop_index(
        op.f("ix_work_item_mentions_created_at"), table_name="work_item_mentions"
    )
    op.drop_index(
        op.f("ix_work_item_mentions_comment_id"), table_name="work_item_mentions"
    )
    op.drop_table("work_item_mentions")
    # ### end Alembic commands ###
