"""add work_item comment and relation tables

Revision ID: 942c379a2580
Revises: f2179cf9e5b7
Create Date: 2026-05-10 22:45:40.281482

"""

import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

from rapidly.core.extensions.sqlalchemy.types import StringEnum
from rapidly.models.work_item_relation import WorkItemRelationType

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "942c379a2580"
down_revision = "f2179cf9e5b7"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_work_item_assignees_rapidly_read_select = PGGrantTable(
        schema="public",
        table="work_item_assignees",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "user_id",
            "work_item_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_work_item_assignees_rapidly_read_select)

    public_work_item_labels_rapidly_read_select = PGGrantTable(
        schema="public",
        table="work_item_labels",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "label_id",
            "modified_at",
            "work_item_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_work_item_labels_rapidly_read_select)

    public_work_items_rapidly_read_select = PGGrantTable(
        schema="public",
        table="work_items",
        columns=[
            "archived_at",
            "completed_at",
            "created_at",
            "deleted_at",
            "description_binary",
            "description_html",
            "description_json",
            "estimate_point_id",
            "id",
            "is_draft",
            "modified_at",
            "name",
            "parent_id",
            "priority",
            "project_id",
            "sequence_number",
            "sort_order",
            "start_date",
            "state_id",
            "target_date",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_work_items_rapidly_read_select)

    op.create_table(
        "work_item_comments",
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("body_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("work_item_comments_actor_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("work_item_comments_work_item_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("work_item_comments_pkey")),
    )
    op.create_index(
        op.f("ix_work_item_comments_actor_id"),
        "work_item_comments",
        ["actor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_comments_created_at"),
        "work_item_comments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_comments_deleted_at"),
        "work_item_comments",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_comments_work_item_id"),
        "work_item_comments",
        ["work_item_id"],
        unique=False,
    )
    op.create_table(
        "work_item_relations",
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("related_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation_type",
            StringEnum(WorkItemRelationType, length=16),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "work_item_id <> related_id",
            name=op.f(
                "work_item_relations_work_item_relations_no_self_link_check_check"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["related_id"],
            ["work_items.id"],
            name=op.f("work_item_relations_related_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("work_item_relations_work_item_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("work_item_relations_pkey")),
        sa.UniqueConstraint(
            "work_item_id",
            "related_id",
            "relation_type",
            name="work_item_relations_work_item_id_related_id_relation_type_key",
        ),
    )
    op.create_index(
        op.f("ix_work_item_relations_created_at"),
        "work_item_relations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_relations_deleted_at"),
        "work_item_relations",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_relations_related_id"),
        "work_item_relations",
        ["related_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_relations_work_item_id"),
        "work_item_relations",
        ["work_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_work_item_relations_work_item_id"), table_name="work_item_relations"
    )
    op.drop_index(
        op.f("ix_work_item_relations_related_id"), table_name="work_item_relations"
    )
    op.drop_index(
        op.f("ix_work_item_relations_deleted_at"), table_name="work_item_relations"
    )
    op.drop_index(
        op.f("ix_work_item_relations_created_at"), table_name="work_item_relations"
    )
    op.drop_table("work_item_relations")
    op.drop_index(
        op.f("ix_work_item_comments_work_item_id"), table_name="work_item_comments"
    )
    op.drop_index(
        op.f("ix_work_item_comments_deleted_at"), table_name="work_item_comments"
    )
    op.drop_index(
        op.f("ix_work_item_comments_created_at"), table_name="work_item_comments"
    )
    op.drop_index(
        op.f("ix_work_item_comments_actor_id"), table_name="work_item_comments"
    )
    op.drop_table("work_item_comments")
    public_work_items_rapidly_read_select = PGGrantTable(
        schema="public",
        table="work_items",
        columns=[
            "archived_at",
            "completed_at",
            "created_at",
            "deleted_at",
            "description_binary",
            "description_html",
            "description_json",
            "estimate_point_id",
            "id",
            "is_draft",
            "modified_at",
            "name",
            "parent_id",
            "priority",
            "project_id",
            "sequence_number",
            "sort_order",
            "start_date",
            "state_id",
            "target_date",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_work_items_rapidly_read_select)

    public_work_item_labels_rapidly_read_select = PGGrantTable(
        schema="public",
        table="work_item_labels",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "label_id",
            "modified_at",
            "work_item_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_work_item_labels_rapidly_read_select)

    public_work_item_assignees_rapidly_read_select = PGGrantTable(
        schema="public",
        table="work_item_assignees",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "user_id",
            "work_item_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_work_item_assignees_rapidly_read_select)

    # ### end Alembic commands ###
