"""add work_item tables

Revision ID: f2179cf9e5b7
Revises: 9c13881d3227
Create Date: 2026-05-10 22:33:42.221625

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from rapidly.core.extensions.sqlalchemy.types import StringEnum
from rapidly.models.work_item import WorkItemPriority

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "f2179cf9e5b7"
down_revision = "9c13881d3227"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_items",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column(
            "description_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("description_html", sa.Text(), nullable=True),
        sa.Column("description_binary", sa.LargeBinary(), nullable=True),
        sa.Column(
            "priority",
            StringEnum(WorkItemPriority, length=16),
            nullable=False,
        ),
        sa.Column("state_id", sa.Uuid(), nullable=False),
        sa.Column("estimate_point_id", sa.Uuid(), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("start_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("target_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("sort_order", sa.Float(), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["estimate_point_id"],
            ["project_estimate_points.id"],
            name=op.f("work_items_estimate_point_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["work_items.id"],
            name=op.f("work_items_parent_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("work_items_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["state_id"],
            ["project_states.id"],
            name=op.f("work_items_state_id_fkey"),
            ondelete="restrict",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("work_items_pkey")),
        sa.UniqueConstraint(
            "project_id",
            "sequence_number",
            name="work_items_project_id_sequence_number_key",
        ),
    )
    op.create_index(
        op.f("ix_work_items_archived_at"), "work_items", ["archived_at"], unique=False
    )
    op.create_index(
        op.f("ix_work_items_created_at"), "work_items", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_work_items_deleted_at"), "work_items", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_work_items_estimate_point_id"),
        "work_items",
        ["estimate_point_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_items_parent_id"), "work_items", ["parent_id"], unique=False
    )
    op.create_index(
        op.f("ix_work_items_project_id"), "work_items", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_work_items_state_id"), "work_items", ["state_id"], unique=False
    )
    op.create_table(
        "work_item_assignees",
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("work_item_assignees_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("work_item_assignees_work_item_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("work_item_assignees_pkey")),
        sa.UniqueConstraint(
            "work_item_id",
            "user_id",
            name="work_item_assignees_work_item_id_user_id_key",
        ),
    )
    op.create_index(
        op.f("ix_work_item_assignees_created_at"),
        "work_item_assignees",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_assignees_deleted_at"),
        "work_item_assignees",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_assignees_user_id"),
        "work_item_assignees",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_assignees_work_item_id"),
        "work_item_assignees",
        ["work_item_id"],
        unique=False,
    )
    op.create_table(
        "work_item_labels",
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("label_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["project_labels.id"],
            name=op.f("work_item_labels_label_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("work_item_labels_work_item_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("work_item_labels_pkey")),
        sa.UniqueConstraint(
            "work_item_id",
            "label_id",
            name="work_item_labels_work_item_id_label_id_key",
        ),
    )
    op.create_index(
        op.f("ix_work_item_labels_created_at"),
        "work_item_labels",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_labels_deleted_at"),
        "work_item_labels",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_labels_label_id"),
        "work_item_labels",
        ["label_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_labels_work_item_id"),
        "work_item_labels",
        ["work_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_work_item_labels_work_item_id"), table_name="work_item_labels"
    )
    op.drop_index(op.f("ix_work_item_labels_label_id"), table_name="work_item_labels")
    op.drop_index(op.f("ix_work_item_labels_deleted_at"), table_name="work_item_labels")
    op.drop_index(op.f("ix_work_item_labels_created_at"), table_name="work_item_labels")
    op.drop_table("work_item_labels")
    op.drop_index(
        op.f("ix_work_item_assignees_work_item_id"), table_name="work_item_assignees"
    )
    op.drop_index(
        op.f("ix_work_item_assignees_user_id"), table_name="work_item_assignees"
    )
    op.drop_index(
        op.f("ix_work_item_assignees_deleted_at"), table_name="work_item_assignees"
    )
    op.drop_index(
        op.f("ix_work_item_assignees_created_at"), table_name="work_item_assignees"
    )
    op.drop_table("work_item_assignees")
    op.drop_index(op.f("ix_work_items_state_id"), table_name="work_items")
    op.drop_index(op.f("ix_work_items_project_id"), table_name="work_items")
    op.drop_index(op.f("ix_work_items_parent_id"), table_name="work_items")
    op.drop_index(op.f("ix_work_items_estimate_point_id"), table_name="work_items")
    op.drop_index(op.f("ix_work_items_deleted_at"), table_name="work_items")
    op.drop_index(op.f("ix_work_items_created_at"), table_name="work_items")
    op.drop_index(op.f("ix_work_items_archived_at"), table_name="work_items")
    op.drop_table("work_items")
    # ### end Alembic commands ###
