"""add stickies table

Revision ID: 368d064b8aed
Revises: 27ed2e68876f
Create Date: 2026-05-20 21:04:16.393696

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "368d064b8aed"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stickies",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "description_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("description_html", sa.Text(), nullable=True),
        sa.Column("description_binary", sa.LargeBinary(), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("sort_order", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("stickies_owner_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("stickies_workspace_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("stickies_pkey")),
    )
    op.create_index(
        op.f("ix_stickies_created_at"), "stickies", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_stickies_deleted_at"), "stickies", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_stickies_owner_id"), "stickies", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_stickies_workspace_id"), "stickies", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stickies_workspace_id"), table_name="stickies")
    op.drop_index(op.f("ix_stickies_owner_id"), table_name="stickies")
    op.drop_index(op.f("ix_stickies_deleted_at"), table_name="stickies")
    op.drop_index(op.f("ix_stickies_created_at"), table_name="stickies")
    op.drop_table("stickies")
    # ### end Alembic commands ###
