"""add work_item_subscribers table

Revision ID: 6da186a491a0
Revises: 27ed2e68876f
Create Date: 2026-05-20 00:11:22.227617

"""

import sqlalchemy as sa
from alembic import op

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "6da186a491a0"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_item_subscribers",
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("work_item_subscribers_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("work_item_subscribers_work_item_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("work_item_subscribers_pkey")),
        sa.UniqueConstraint(
            "work_item_id",
            "user_id",
            name="work_item_subscribers_work_item_id_user_id_key",
        ),
    )
    op.create_index(
        op.f("ix_work_item_subscribers_created_at"),
        "work_item_subscribers",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_subscribers_deleted_at"),
        "work_item_subscribers",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_subscribers_user_id"),
        "work_item_subscribers",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_subscribers_work_item_id"),
        "work_item_subscribers",
        ["work_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_work_item_subscribers_work_item_id"),
        table_name="work_item_subscribers",
    )
    op.drop_index(
        op.f("ix_work_item_subscribers_user_id"), table_name="work_item_subscribers"
    )
    op.drop_index(
        op.f("ix_work_item_subscribers_deleted_at"), table_name="work_item_subscribers"
    )
    op.drop_index(
        op.f("ix_work_item_subscribers_created_at"), table_name="work_item_subscribers"
    )
    op.drop_table("work_item_subscribers")
    # ### end Alembic commands ###
