"""add project_module_members and project_module_links tables

Revision ID: 049cc44f35a6
Revises: 27ed2e68876f
Create Date: 2026-05-20 20:16:34.807068

"""

import sqlalchemy as sa
from alembic import op

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "049cc44f35a6"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_module_links",
        sa.Column("module_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("project_module_links_created_by_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["project_modules.id"],
            name=op.f("project_module_links_module_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_module_links_pkey")),
    )
    op.create_index(
        op.f("ix_project_module_links_created_at"),
        "project_module_links",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_module_links_created_by_id"),
        "project_module_links",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_module_links_deleted_at"),
        "project_module_links",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_module_links_module_id"),
        "project_module_links",
        ["module_id"],
        unique=False,
    )
    op.create_table(
        "project_module_members",
        sa.Column("module_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["project_modules.id"],
            name=op.f("project_module_members_module_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("project_module_members_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_module_members_pkey")),
        sa.UniqueConstraint(
            "module_id", "user_id", name="project_module_members_module_id_user_id_key"
        ),
    )
    op.create_index(
        op.f("ix_project_module_members_created_at"),
        "project_module_members",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_module_members_deleted_at"),
        "project_module_members",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_module_members_module_id"),
        "project_module_members",
        ["module_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_module_members_user_id"),
        "project_module_members",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_module_members_user_id"), table_name="project_module_members"
    )
    op.drop_index(
        op.f("ix_project_module_members_module_id"), table_name="project_module_members"
    )
    op.drop_index(
        op.f("ix_project_module_members_deleted_at"),
        table_name="project_module_members",
    )
    op.drop_index(
        op.f("ix_project_module_members_created_at"),
        table_name="project_module_members",
    )
    op.drop_table("project_module_members")
    op.drop_index(
        op.f("ix_project_module_links_module_id"), table_name="project_module_links"
    )
    op.drop_index(
        op.f("ix_project_module_links_deleted_at"), table_name="project_module_links"
    )
    op.drop_index(
        op.f("ix_project_module_links_created_by_id"), table_name="project_module_links"
    )
    op.drop_index(
        op.f("ix_project_module_links_created_at"), table_name="project_module_links"
    )
    op.drop_table("project_module_links")
    # ### end Alembic commands ###
