"""add intake_work_items table

Revision ID: 023e0ce49642
Revises: 27ed2e68876f
Create Date: 2026-05-20 21:46:41.913668

"""

import sqlalchemy as sa
from alembic import op

# Rapidly Custom Imports
from rapidly.core.extensions.sqlalchemy.types import StringEnum
from rapidly.models.intake_work_item import IntakeSource, IntakeStatus

# revision identifiers, used by Alembic.
revision = "023e0ce49642"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intake_work_items",
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            StringEnum(IntakeStatus, length=16),
            nullable=False,
        ),
        sa.Column(
            "source",
            StringEnum(IntakeSource, length=16),
            nullable=False,
        ),
        sa.Column("source_email", sa.String(length=320), nullable=True),
        sa.Column("snoozed_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("duplicate_to_id", sa.Uuid(), nullable=True),
        sa.Column("triaged_by_id", sa.Uuid(), nullable=True),
        sa.Column("triaged_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["duplicate_to_id"],
            ["work_items.id"],
            name=op.f("intake_work_items_duplicate_to_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["triaged_by_id"],
            ["users.id"],
            name=op.f("intake_work_items_triaged_by_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("intake_work_items_work_item_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("intake_work_items_pkey")),
        sa.UniqueConstraint("work_item_id", name="intake_work_items_work_item_id_key"),
    )
    op.create_index(
        op.f("ix_intake_work_items_created_at"),
        "intake_work_items",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_intake_work_items_deleted_at"),
        "intake_work_items",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_intake_work_items_duplicate_to_id"),
        "intake_work_items",
        ["duplicate_to_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_intake_work_items_status"),
        "intake_work_items",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_intake_work_items_triaged_by_id"),
        "intake_work_items",
        ["triaged_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_intake_work_items_work_item_id"),
        "intake_work_items",
        ["work_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_intake_work_items_work_item_id"), table_name="intake_work_items"
    )
    op.drop_index(
        op.f("ix_intake_work_items_triaged_by_id"), table_name="intake_work_items"
    )
    op.drop_index(op.f("ix_intake_work_items_status"), table_name="intake_work_items")
    op.drop_index(
        op.f("ix_intake_work_items_duplicate_to_id"), table_name="intake_work_items"
    )
    op.drop_index(
        op.f("ix_intake_work_items_deleted_at"), table_name="intake_work_items"
    )
    op.drop_index(
        op.f("ix_intake_work_items_created_at"), table_name="intake_work_items"
    )
    op.drop_table("intake_work_items")
    # ### end Alembic commands ###
