"""add work_item_links table

Revision ID: 02350500ee7a
Revises: 27ed2e68876f
Create Date: 2026-05-19 22:03:24.031764

"""

import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "02350500ee7a"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_project_pages_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_pages",
        columns=[
            "access",
            "archived_at",
            "created_at",
            "deleted_at",
            "description_binary",
            "description_html",
            "description_json",
            "id",
            "is_locked",
            "modified_at",
            "name",
            "owner_id",
            "parent_id",
            "project_id",
            "slug",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_project_pages_rapidly_read_select)

    public_user_favorites_rapidly_read_select = PGGrantTable(
        schema="public",
        table="user_favorites",
        columns=[
            "created_at",
            "deleted_at",
            "entity_id",
            "entity_type",
            "id",
            "modified_at",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_user_favorites_rapidly_read_select)

    op.create_table(
        "work_item_links",
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("work_item_links_created_by_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("work_item_links_work_item_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("work_item_links_pkey")),
    )
    op.create_index(
        op.f("ix_work_item_links_created_at"),
        "work_item_links",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_links_created_by_id"),
        "work_item_links",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_links_deleted_at"),
        "work_item_links",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_links_work_item_id"),
        "work_item_links",
        ["work_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_item_links_work_item_id"), table_name="work_item_links")
    op.drop_index(op.f("ix_work_item_links_deleted_at"), table_name="work_item_links")
    op.drop_index(
        op.f("ix_work_item_links_created_by_id"), table_name="work_item_links"
    )
    op.drop_index(op.f("ix_work_item_links_created_at"), table_name="work_item_links")
    op.drop_table("work_item_links")
    public_user_favorites_rapidly_read_select = PGGrantTable(
        schema="public",
        table="user_favorites",
        columns=[
            "created_at",
            "deleted_at",
            "entity_id",
            "entity_type",
            "id",
            "modified_at",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_user_favorites_rapidly_read_select)

    public_project_pages_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_pages",
        columns=[
            "access",
            "archived_at",
            "created_at",
            "deleted_at",
            "description_binary",
            "description_html",
            "description_json",
            "id",
            "is_locked",
            "modified_at",
            "name",
            "owner_id",
            "parent_id",
            "project_id",
            "slug",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_project_pages_rapidly_read_select)

    # ### end Alembic commands ###
