"""add project_module tables

Revision ID: 6fe332564f08
Revises: db862b1bb5a5
Create Date: 2026-05-12 20:08:57.104852

"""

from enum import StrEnum

import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text

from rapidly.core.extensions.sqlalchemy.types import StringEnum


class ModuleStatus(StrEnum):
    """Inlined for M1.5 post-deletion compatibility."""

    planned = "planned"
    in_progress = "in_progress"
    paused = "paused"
    completed = "completed"
    cancelled = "cancelled"


# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "6fe332564f08"
down_revision = "db862b1bb5a5"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_project_cycle_work_items_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_cycle_work_items",
        columns=[
            "created_at",
            "cycle_id",
            "deleted_at",
            "id",
            "modified_at",
            "work_item_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_project_cycle_work_items_rapidly_read_select)

    public_project_cycles_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_cycles",
        columns=[
            "archived_at",
            "created_at",
            "deleted_at",
            "description",
            "end_date",
            "id",
            "modified_at",
            "name",
            "owner_id",
            "project_id",
            "start_date",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_project_cycles_rapidly_read_select)

    op.create_table(
        "project_modules",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            StringEnum(ModuleStatus, length=16),
            nullable=False,
        ),
        sa.Column("start_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("target_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("archived_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["users.id"],
            name=op.f("project_modules_lead_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("project_modules_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_modules_pkey")),
        sa.UniqueConstraint(
            "project_id", "name", name="project_modules_project_id_name_key"
        ),
    )
    op.create_index(
        op.f("ix_project_modules_archived_at"),
        "project_modules",
        ["archived_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_modules_created_at"),
        "project_modules",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_modules_deleted_at"),
        "project_modules",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_modules_lead_id"), "project_modules", ["lead_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_modules_project_id"),
        "project_modules",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "project_module_work_items",
        sa.Column("module_id", sa.Uuid(), nullable=False),
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["project_modules.id"],
            name=op.f("project_module_work_items_module_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("project_module_work_items_work_item_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_module_work_items_pkey")),
        sa.UniqueConstraint(
            "module_id",
            "work_item_id",
            name="project_module_work_items_module_id_work_item_id_key",
        ),
    )
    op.create_index(
        op.f("ix_project_module_work_items_created_at"),
        "project_module_work_items",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_module_work_items_deleted_at"),
        "project_module_work_items",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_module_work_items_module_id"),
        "project_module_work_items",
        ["module_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_module_work_items_work_item_id"),
        "project_module_work_items",
        ["work_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_module_work_items_work_item_id"),
        table_name="project_module_work_items",
    )
    op.drop_index(
        op.f("ix_project_module_work_items_module_id"),
        table_name="project_module_work_items",
    )
    op.drop_index(
        op.f("ix_project_module_work_items_deleted_at"),
        table_name="project_module_work_items",
    )
    op.drop_index(
        op.f("ix_project_module_work_items_created_at"),
        table_name="project_module_work_items",
    )
    op.drop_table("project_module_work_items")
    op.drop_index(op.f("ix_project_modules_project_id"), table_name="project_modules")
    op.drop_index(op.f("ix_project_modules_lead_id"), table_name="project_modules")
    op.drop_index(op.f("ix_project_modules_deleted_at"), table_name="project_modules")
    op.drop_index(op.f("ix_project_modules_created_at"), table_name="project_modules")
    op.drop_index(op.f("ix_project_modules_archived_at"), table_name="project_modules")
    op.drop_table("project_modules")
    public_project_cycles_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_cycles",
        columns=[
            "archived_at",
            "created_at",
            "deleted_at",
            "description",
            "end_date",
            "id",
            "modified_at",
            "name",
            "owner_id",
            "project_id",
            "start_date",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_project_cycles_rapidly_read_select)

    public_project_cycle_work_items_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_cycle_work_items",
        columns=[
            "created_at",
            "cycle_id",
            "deleted_at",
            "id",
            "modified_at",
            "work_item_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_project_cycle_work_items_rapidly_read_select)

    # ### end Alembic commands ###
