"""add projects domain tables

Revision ID: 89780c8c1f1f
Revises: 94654a5645a5
Create Date: 2026-05-10 21:23:16.393380

"""

import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text

from rapidly.core.extensions.sqlalchemy.types import StringEnum
from rapidly.models.project import ProjectVisibility
from rapidly.models.project_estimate import EstimateType
from rapidly.models.project_member import ProjectMemberRole
from rapidly.models.project_state import StateGroup

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "89780c8c1f1f"
down_revision = "94654a5645a5"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_accounts_rapidly_read_select = PGGrantTable(
        schema="public",
        table="accounts",
        columns=[
            "account_type",
            "admin_id",
            "billing_additional_info",
            "billing_address",
            "billing_name",
            "billing_notes",
            "business_type",
            "campaign_id",
            "country",
            "created_at",
            "credit_balance",
            "currency",
            "data",
            "deleted_at",
            "email",
            "id",
            "is_charges_enabled",
            "is_details_submitted",
            "is_payouts_enabled",
            "modified_at",
            "next_review_threshold",
            "open_collective_slug",
            "platform_fee_fixed",
            "platform_fee_percent",
            "processor_fees_applicable",
            "status",
            "stripe_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_accounts_rapidly_read_select)

    public_alembic_version_rapidly_read_select = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_alembic_version_rapidly_read_select)

    public_custom_fields_rapidly_read_select = PGGrantTable(
        schema="public",
        table="custom_fields",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "name",
            "properties",
            "slug",
            "type",
            "user_metadata",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_custom_fields_rapidly_read_select)

    public_customer_session_codes_rapidly_read_select = PGGrantTable(
        schema="public",
        table="customer_session_codes",
        columns=[
            "code",
            "created_at",
            "customer_id",
            "deleted_at",
            "email",
            "expires_at",
            "id",
            "modified_at",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_customer_session_codes_rapidly_read_select)

    public_customer_sessions_rapidly_read_select = PGGrantTable(
        schema="public",
        table="customer_sessions",
        columns=[
            "created_at",
            "customer_id",
            "deleted_at",
            "expires_at",
            "id",
            "modified_at",
            "return_url",
            "token",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_customer_sessions_rapidly_read_select)

    public_customers_rapidly_read_select = PGGrantTable(
        schema="public",
        table="customers",
        columns=[
            "billing_address",
            "billing_name",
            "created_at",
            "default_payment_method_id",
            "deleted_at",
            "email",
            "email_verified",
            "external_id",
            "id",
            "invoice_next_number",
            "legacy_user_id",
            "meters_dirtied_at",
            "meters_updated_at",
            "modified_at",
            "name",
            "oauth_accounts",
            "search_vector",
            "short_id",
            "stripe_customer_id",
            "type",
            "user_metadata",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_customers_rapidly_read_select)

    public_email_verification_rapidly_read_select = PGGrantTable(
        schema="public",
        table="email_verification",
        columns=[
            "created_at",
            "deleted_at",
            "email",
            "expires_at",
            "id",
            "modified_at",
            "token_hash",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_email_verification_rapidly_read_select)

    public_event_types_rapidly_read_select = PGGrantTable(
        schema="public",
        table="event_types",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "label",
            "label_property_selector",
            "modified_at",
            "name",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_event_types_rapidly_read_select)

    public_events_rapidly_read_select = PGGrantTable(
        schema="public",
        table="events",
        columns=[
            "customer_id",
            "event_type_id",
            "external_customer_id",
            "external_id",
            "external_member_id",
            "id",
            "ingested_at",
            "member_id",
            "name",
            "parent_id",
            "root_id",
            "source",
            "timestamp",
            "user_metadata",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_events_rapidly_read_select)

    public_events_closure_rapidly_read_select = PGGrantTable(
        schema="public",
        table="events_closure",
        columns=["ancestor_id", "depth", "descendant_id"],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_events_closure_rapidly_read_select)

    public_external_events_rapidly_read_select = PGGrantTable(
        schema="public",
        table="external_events",
        columns=[
            "created_at",
            "data",
            "deleted_at",
            "external_id",
            "handled_at",
            "id",
            "modified_at",
            "source",
            "task_name",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_external_events_rapidly_read_select)

    public_file_share_downloads_rapidly_read_select = PGGrantTable(
        schema="public",
        table="file_share_downloads",
        columns=[
            "created_at",
            "deleted_at",
            "downloader_ip_hash",
            "id",
            "modified_at",
            "session_id",
            "slot_number",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_file_share_downloads_rapidly_read_select)

    public_file_share_payments_rapidly_read_select = PGGrantTable(
        schema="public",
        table="file_share_payments",
        columns=[
            "amount_cents",
            "buyer_email",
            "buyer_ip_hash",
            "buyer_name",
            "created_at",
            "currency",
            "customer_id",
            "deleted_at",
            "id",
            "modified_at",
            "payment_id",
            "payment_method_id",
            "platform_fee_cents",
            "session_id",
            "status",
            "stripe_checkout_session_id",
            "stripe_payment_intent_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_file_share_payments_rapidly_read_select)

    public_file_share_reports_rapidly_read_select = PGGrantTable(
        schema="public",
        table="file_share_reports",
        columns=[
            "admin_notes",
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "reason",
            "reporter_ip_hash",
            "reviewed_at",
            "session_id",
            "status",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_file_share_reports_rapidly_read_select)

    public_file_share_sessions_rapidly_read_select = PGGrantTable(
        schema="public",
        table="file_share_sessions",
        columns=[
            "activated_at",
            "completed_at",
            "created_at",
            "creator_ip_hash",
            "currency",
            "deleted_at",
            "download_count",
            "expires_at",
            "file_name",
            "file_size_bytes",
            "id",
            "long_slug",
            "max_downloads",
            "modified_at",
            "price_cents",
            "share_id",
            "short_slug",
            "status",
            "title",
            "ttl_seconds",
            "user_id",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_file_share_sessions_rapidly_read_select)

    public_files_rapidly_read_select = PGGrantTable(
        schema="public",
        table="files",
        columns=[
            "checksum_etag",
            "checksum_sha256_base64",
            "checksum_sha256_hex",
            "created_at",
            "deleted_at",
            "id",
            "is_enabled",
            "is_uploaded",
            "last_modified_at",
            "mime_type",
            "modified_at",
            "name",
            "path",
            "scan_result",
            "scan_status",
            "scanned_at",
            "service",
            "size",
            "storage_version",
            "version",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_files_rapidly_read_select)

    public_login_codes_rapidly_read_select = PGGrantTable(
        schema="public",
        table="login_codes",
        columns=[
            "code_hash",
            "created_at",
            "deleted_at",
            "email",
            "expires_at",
            "id",
            "modified_at",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_login_codes_rapidly_read_select)

    public_member_sessions_rapidly_read_select = PGGrantTable(
        schema="public",
        table="member_sessions",
        columns=[
            "created_at",
            "deleted_at",
            "expires_at",
            "id",
            "member_id",
            "modified_at",
            "return_url",
            "token",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_member_sessions_rapidly_read_select)

    public_members_rapidly_read_select = PGGrantTable(
        schema="public",
        table="members",
        columns=[
            "created_at",
            "customer_id",
            "deleted_at",
            "email",
            "external_id",
            "id",
            "modified_at",
            "name",
            "oauth_accounts",
            "role",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_members_rapidly_read_select)

    public_notification_recipients_rapidly_read_select = PGGrantTable(
        schema="public",
        table="notification_recipients",
        columns=[
            "created_at",
            "deleted_at",
            "expo_push_token",
            "id",
            "modified_at",
            "platform",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_notification_recipients_rapidly_read_select)

    public_notifications_rapidly_read_select = PGGrantTable(
        schema="public",
        table="notifications",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "payload",
            "type",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_notifications_rapidly_read_select)

    public_oauth2_authorization_codes_rapidly_read_select = PGGrantTable(
        schema="public",
        table="oauth2_authorization_codes",
        columns=[
            "acr",
            "amr",
            "auth_time",
            "client_id",
            "code",
            "code_challenge",
            "code_challenge_method",
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "nonce",
            "redirect_uri",
            "response_type",
            "scope",
            "sub_type",
            "user_id",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_oauth2_authorization_codes_rapidly_read_select)

    public_oauth2_clients_rapidly_read_select = PGGrantTable(
        schema="public",
        table="oauth2_clients",
        columns=[
            "client_id",
            "client_id_issued_at",
            "client_metadata",
            "client_secret",
            "client_secret_expires_at",
            "created_at",
            "deleted_at",
            "first_party",
            "id",
            "modified_at",
            "rate_limit_group",
            "registration_access_token",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_oauth2_clients_rapidly_read_select)

    public_oauth2_grants_rapidly_read_select = PGGrantTable(
        schema="public",
        table="oauth2_grants",
        columns=[
            "client_id",
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "scope",
            "user_id",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_oauth2_grants_rapidly_read_select)

    public_oauth2_tokens_rapidly_read_select = PGGrantTable(
        schema="public",
        table="oauth2_tokens",
        columns=[
            "access_token",
            "access_token_revoked_at",
            "client_id",
            "created_at",
            "deleted_at",
            "expires_in",
            "id",
            "issued_at",
            "modified_at",
            "nonce",
            "refresh_token",
            "refresh_token_revoked_at",
            "scope",
            "sub_type",
            "token_type",
            "user_id",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_oauth2_tokens_rapidly_read_select)

    public_oauth_accounts_rapidly_read_select = PGGrantTable(
        schema="public",
        table="oauth_accounts",
        columns=[
            "access_token",
            "account_email",
            "account_id",
            "account_username",
            "created_at",
            "deleted_at",
            "expires_at",
            "id",
            "modified_at",
            "platform",
            "refresh_token",
            "refresh_token_expires_at",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_oauth_accounts_rapidly_read_select)

    public_payment_methods_rapidly_read_select = PGGrantTable(
        schema="public",
        table="payment_methods",
        columns=[
            "created_at",
            "customer_id",
            "deleted_at",
            "id",
            "method_metadata",
            "modified_at",
            "processor",
            "processor_id",
            "type",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_payment_methods_rapidly_read_select)

    public_payments_rapidly_read_select = PGGrantTable(
        schema="public",
        table="payments",
        columns=[
            "amount",
            "created_at",
            "currency",
            "customer_email",
            "decline_message",
            "decline_reason",
            "deleted_at",
            "id",
            "method",
            "method_metadata",
            "modified_at",
            "processor",
            "processor_id",
            "processor_metadata",
            "risk_level",
            "risk_score",
            "status",
            "wallet_id",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_payments_rapidly_read_select)

    public_share_custom_fields_rapidly_read_select = PGGrantTable(
        schema="public",
        table="share_custom_fields",
        columns=[
            "created_at",
            "custom_field_id",
            "deleted_at",
            "id",
            "modified_at",
            "order",
            "required",
            "share_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_share_custom_fields_rapidly_read_select)

    public_share_medias_rapidly_read_select = PGGrantTable(
        schema="public",
        table="share_medias",
        columns=[
            "created_at",
            "deleted_at",
            "file_id",
            "id",
            "modified_at",
            "order",
            "share_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_share_medias_rapidly_read_select)

    public_share_prices_rapidly_read_select = PGGrantTable(
        schema="public",
        table="share_prices",
        columns=[
            "amount_type",
            "cap_amount",
            "created_at",
            "deleted_at",
            "id",
            "is_archived",
            "maximum_amount",
            "meter_id",
            "minimum_amount",
            "modified_at",
            "preset_amount",
            "price_amount",
            "price_currency",
            "seat_tiers",
            "share_id",
            "source",
            "unit_amount",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_share_prices_rapidly_read_select)

    public_shares_rapidly_read_select = PGGrantTable(
        schema="public",
        table="shares",
        columns=[
            "created_at",
            "deleted_at",
            "description",
            "id",
            "is_archived",
            "modified_at",
            "name",
            "search_vector",
            "user_metadata",
            "visibility",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_shares_rapidly_read_select)

    public_user_notifications_rapidly_read_select = PGGrantTable(
        schema="public",
        table="user_notifications",
        columns=["last_read_notification_id", "user_id"],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_user_notifications_rapidly_read_select)

    public_user_sessions_rapidly_read_select = PGGrantTable(
        schema="public",
        table="user_sessions",
        columns=[
            "created_at",
            "deleted_at",
            "expires_at",
            "id",
            "is_impersonation",
            "modified_at",
            "scopes",
            "token",
            "user_agent",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_user_sessions_rapidly_read_select)

    public_users_rapidly_read_select = PGGrantTable(
        schema="public",
        table="users",
        columns=[
            "accepted_terms_of_service",
            "account_id",
            "avatar_url",
            "blocked_at",
            "created_at",
            "deleted_at",
            "email",
            "email_verified",
            "id",
            "identity_verification_id",
            "identity_verification_status",
            "is_admin",
            "meta",
            "modified_at",
            "stripe_customer_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_users_rapidly_read_select)

    public_wallet_transactions_rapidly_read_select = PGGrantTable(
        schema="public",
        table="wallet_transactions",
        columns=["amount", "currency", "id", "timestamp", "wallet_id"],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_wallet_transactions_rapidly_read_select)

    public_wallets_rapidly_read_select = PGGrantTable(
        schema="public",
        table="wallets",
        columns=[
            "created_at",
            "currency",
            "customer_id",
            "deleted_at",
            "id",
            "modified_at",
            "type",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_wallets_rapidly_read_select)

    public_webhook_deliveries_rapidly_read_select = PGGrantTable(
        schema="public",
        table="webhook_deliveries",
        columns=[
            "created_at",
            "deleted_at",
            "http_code",
            "id",
            "modified_at",
            "response",
            "succeeded",
            "webhook_endpoint_id",
            "webhook_event_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_webhook_deliveries_rapidly_read_select)

    public_webhook_endpoints_rapidly_read_select = PGGrantTable(
        schema="public",
        table="webhook_endpoints",
        columns=[
            "created_at",
            "deleted_at",
            "enabled",
            "events",
            "format",
            "id",
            "modified_at",
            "secret",
            "url",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_webhook_endpoints_rapidly_read_select)

    public_webhook_events_rapidly_read_select = PGGrantTable(
        schema="public",
        table="webhook_events",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "last_http_code",
            "modified_at",
            "payload",
            "skipped",
            "succeeded",
            "type",
            "webhook_endpoint_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_webhook_events_rapidly_read_select)

    public_workspace_access_tokens_rapidly_read_select = PGGrantTable(
        schema="public",
        table="workspace_access_tokens",
        columns=[
            "comment",
            "created_at",
            "deleted_at",
            "expires_at",
            "id",
            "last_used_at",
            "modified_at",
            "scope",
            "token",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_workspace_access_tokens_rapidly_read_select)

    public_workspace_memberships_rapidly_read_select = PGGrantTable(
        schema="public",
        table="workspace_memberships",
        columns=["created_at", "deleted_at", "modified_at", "user_id", "workspace_id"],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_workspace_memberships_rapidly_read_select)

    public_workspace_reviews_rapidly_read_select = PGGrantTable(
        schema="public",
        table="workspace_reviews",
        columns=[
            "appeal_decision",
            "appeal_reason",
            "appeal_reviewed_at",
            "appeal_submitted_at",
            "created_at",
            "deleted_at",
            "id",
            "model_used",
            "modified_at",
            "reason",
            "risk_score",
            "timed_out",
            "validated_at",
            "verdict",
            "violated_sections",
            "workspace_details_snapshot",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_workspace_reviews_rapidly_read_select)

    public_workspaces_rapidly_read_select = PGGrantTable(
        schema="public",
        table="workspaces",
        columns=[
            "account_id",
            "ai_onboarding_completed_at",
            "avatar_url",
            "bio",
            "blocked_at",
            "blog",
            "company",
            "created_at",
            "customer_email_settings",
            "customer_invoice_next_number",
            "customer_invoice_prefix",
            "customer_portal_settings",
            "default_presentment_currency",
            "deleted_at",
            "details",
            "details_submitted_at",
            "email",
            "feature_settings",
            "id",
            "initially_reviewed_at",
            "internal_notes",
            "location",
            "modified_at",
            "name",
            "next_review_threshold",
            "notification_settings",
            "onboarded_at",
            "profile_settings",
            "rate_limit_group",
            "slug",
            "socials",
            "status",
            "status_updated_at",
            "twitter_username",
            "website",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_workspaces_rapidly_read_select)

    op.create_table(
        "projects",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("identifier", sa.String(length=12), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "visibility",
            StringEnum(ProjectVisibility, length=16),
            nullable=False,
        ),
        sa.Column("emoji", sa.String(length=16), nullable=True),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.Column("cover_image_url", sa.String(length=2048), nullable=True),
        sa.Column("is_cycles_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_modules_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_views_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_pages_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_intake_enabled", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("projects_owner_id_fkey"),
            ondelete="restrict",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("projects_workspace_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("projects_pkey")),
        sa.UniqueConstraint(
            "workspace_id", "identifier", name="projects_workspace_id_identifier_key"
        ),
        sa.UniqueConstraint(
            "workspace_id", "slug", name="projects_workspace_id_slug_key"
        ),
    )
    op.create_index(
        op.f("ix_projects_archived_at"), "projects", ["archived_at"], unique=False
    )
    op.create_index(
        op.f("ix_projects_created_at"), "projects", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_projects_deleted_at"), "projects", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_projects_workspace_id"), "projects", ["workspace_id"], unique=False
    )
    op.create_table(
        "project_estimates",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column(
            "type",
            StringEnum(EstimateType, length=16),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("project_estimates_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_estimates_pkey")),
        sa.UniqueConstraint(
            "project_id", "name", name="project_estimates_project_id_name_key"
        ),
    )
    op.create_index(
        op.f("ix_project_estimates_created_at"),
        "project_estimates",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_estimates_deleted_at"),
        "project_estimates",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_estimates_project_id"),
        "project_estimates",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "project_labels",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["project_labels.id"],
            name=op.f("project_labels_parent_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("project_labels_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_labels_pkey")),
        sa.UniqueConstraint(
            "project_id", "name", name="project_labels_project_id_name_key"
        ),
    )
    op.create_index(
        op.f("ix_project_labels_created_at"),
        "project_labels",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_labels_deleted_at"),
        "project_labels",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_labels_parent_id"),
        "project_labels",
        ["parent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_labels_project_id"),
        "project_labels",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "project_members",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            StringEnum(ProjectMemberRole, length=16),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("project_members_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("project_members_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_members_pkey")),
        sa.UniqueConstraint(
            "project_id", "user_id", name="project_members_project_id_user_id_key"
        ),
    )
    op.create_index(
        op.f("ix_project_members_created_at"),
        "project_members",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_members_deleted_at"),
        "project_members",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_members_project_id"),
        "project_members",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_members_user_id"), "project_members", ["user_id"], unique=False
    )
    op.create_table(
        "project_states",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column(
            "group",
            StringEnum(StateGroup, length=16),
            nullable=False,
        ),
        sa.Column("sequence", sa.Float(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("project_states_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_states_pkey")),
        sa.UniqueConstraint(
            "project_id", "name", name="project_states_project_id_name_key"
        ),
    )
    op.create_index(
        op.f("ix_project_states_created_at"),
        "project_states",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_states_deleted_at"),
        "project_states",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_states_project_id"),
        "project_states",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "project_estimate_points",
        sa.Column("estimate_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["estimate_id"],
            ["project_estimates.id"],
            name=op.f("project_estimate_points_estimate_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_estimate_points_pkey")),
        sa.UniqueConstraint(
            "estimate_id", "key", name="project_estimate_points_estimate_id_key_key"
        ),
    )
    op.create_index(
        op.f("ix_project_estimate_points_created_at"),
        "project_estimate_points",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_estimate_points_deleted_at"),
        "project_estimate_points",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_estimate_points_estimate_id"),
        "project_estimate_points",
        ["estimate_id"],
        unique=False,
    )
    op.alter_column(
        "oauth_accounts",
        "access_token",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=4096),
        existing_nullable=False,
    )
    op.alter_column(
        "oauth_accounts",
        "refresh_token",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=4096),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "oauth_accounts",
        "refresh_token",
        existing_type=sa.String(length=4096),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=True,
    )
    op.alter_column(
        "oauth_accounts",
        "access_token",
        existing_type=sa.String(length=4096),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_project_estimate_points_estimate_id"),
        table_name="project_estimate_points",
    )
    op.drop_index(
        op.f("ix_project_estimate_points_deleted_at"),
        table_name="project_estimate_points",
    )
    op.drop_index(
        op.f("ix_project_estimate_points_created_at"),
        table_name="project_estimate_points",
    )
    op.drop_table("project_estimate_points")
    op.drop_index(op.f("ix_project_states_project_id"), table_name="project_states")
    op.drop_index(op.f("ix_project_states_deleted_at"), table_name="project_states")
    op.drop_index(op.f("ix_project_states_created_at"), table_name="project_states")
    op.drop_table("project_states")
    op.drop_index(op.f("ix_project_members_user_id"), table_name="project_members")
    op.drop_index(op.f("ix_project_members_project_id"), table_name="project_members")
    op.drop_index(op.f("ix_project_members_deleted_at"), table_name="project_members")
    op.drop_index(op.f("ix_project_members_created_at"), table_name="project_members")
    op.drop_table("project_members")
    op.drop_index(op.f("ix_project_labels_project_id"), table_name="project_labels")
    op.drop_index(op.f("ix_project_labels_parent_id"), table_name="project_labels")
    op.drop_index(op.f("ix_project_labels_deleted_at"), table_name="project_labels")
    op.drop_index(op.f("ix_project_labels_created_at"), table_name="project_labels")
    op.drop_table("project_labels")
    op.drop_index(
        op.f("ix_project_estimates_project_id"), table_name="project_estimates"
    )
    op.drop_index(
        op.f("ix_project_estimates_deleted_at"), table_name="project_estimates"
    )
    op.drop_index(
        op.f("ix_project_estimates_created_at"), table_name="project_estimates"
    )
    op.drop_table("project_estimates")
    op.drop_index(op.f("ix_projects_workspace_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_deleted_at"), table_name="projects")
    op.drop_index(op.f("ix_projects_created_at"), table_name="projects")
    op.drop_index(op.f("ix_projects_archived_at"), table_name="projects")
    op.drop_table("projects")
    public_workspaces_rapidly_read_select = PGGrantTable(
        schema="public",
        table="workspaces",
        columns=[
            "account_id",
            "ai_onboarding_completed_at",
            "avatar_url",
            "bio",
            "blocked_at",
            "blog",
            "company",
            "created_at",
            "customer_email_settings",
            "customer_invoice_next_number",
            "customer_invoice_prefix",
            "customer_portal_settings",
            "default_presentment_currency",
            "deleted_at",
            "details",
            "details_submitted_at",
            "email",
            "feature_settings",
            "id",
            "initially_reviewed_at",
            "internal_notes",
            "location",
            "modified_at",
            "name",
            "next_review_threshold",
            "notification_settings",
            "onboarded_at",
            "profile_settings",
            "rate_limit_group",
            "slug",
            "socials",
            "status",
            "status_updated_at",
            "twitter_username",
            "website",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_workspaces_rapidly_read_select)

    public_workspace_reviews_rapidly_read_select = PGGrantTable(
        schema="public",
        table="workspace_reviews",
        columns=[
            "appeal_decision",
            "appeal_reason",
            "appeal_reviewed_at",
            "appeal_submitted_at",
            "created_at",
            "deleted_at",
            "id",
            "model_used",
            "modified_at",
            "reason",
            "risk_score",
            "timed_out",
            "validated_at",
            "verdict",
            "violated_sections",
            "workspace_details_snapshot",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_workspace_reviews_rapidly_read_select)

    public_workspace_memberships_rapidly_read_select = PGGrantTable(
        schema="public",
        table="workspace_memberships",
        columns=["created_at", "deleted_at", "modified_at", "user_id", "workspace_id"],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_workspace_memberships_rapidly_read_select)

    public_workspace_access_tokens_rapidly_read_select = PGGrantTable(
        schema="public",
        table="workspace_access_tokens",
        columns=[
            "comment",
            "created_at",
            "deleted_at",
            "expires_at",
            "id",
            "last_used_at",
            "modified_at",
            "scope",
            "token",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_workspace_access_tokens_rapidly_read_select)

    public_webhook_events_rapidly_read_select = PGGrantTable(
        schema="public",
        table="webhook_events",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "last_http_code",
            "modified_at",
            "payload",
            "skipped",
            "succeeded",
            "type",
            "webhook_endpoint_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_webhook_events_rapidly_read_select)

    public_webhook_endpoints_rapidly_read_select = PGGrantTable(
        schema="public",
        table="webhook_endpoints",
        columns=[
            "created_at",
            "deleted_at",
            "enabled",
            "events",
            "format",
            "id",
            "modified_at",
            "secret",
            "url",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_webhook_endpoints_rapidly_read_select)

    public_webhook_deliveries_rapidly_read_select = PGGrantTable(
        schema="public",
        table="webhook_deliveries",
        columns=[
            "created_at",
            "deleted_at",
            "http_code",
            "id",
            "modified_at",
            "response",
            "succeeded",
            "webhook_endpoint_id",
            "webhook_event_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_webhook_deliveries_rapidly_read_select)

    public_wallets_rapidly_read_select = PGGrantTable(
        schema="public",
        table="wallets",
        columns=[
            "created_at",
            "currency",
            "customer_id",
            "deleted_at",
            "id",
            "modified_at",
            "type",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_wallets_rapidly_read_select)

    public_wallet_transactions_rapidly_read_select = PGGrantTable(
        schema="public",
        table="wallet_transactions",
        columns=["amount", "currency", "id", "timestamp", "wallet_id"],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_wallet_transactions_rapidly_read_select)

    public_users_rapidly_read_select = PGGrantTable(
        schema="public",
        table="users",
        columns=[
            "accepted_terms_of_service",
            "account_id",
            "avatar_url",
            "blocked_at",
            "created_at",
            "deleted_at",
            "email",
            "email_verified",
            "id",
            "identity_verification_id",
            "identity_verification_status",
            "is_admin",
            "meta",
            "modified_at",
            "stripe_customer_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_users_rapidly_read_select)

    public_user_sessions_rapidly_read_select = PGGrantTable(
        schema="public",
        table="user_sessions",
        columns=[
            "created_at",
            "deleted_at",
            "expires_at",
            "id",
            "is_impersonation",
            "modified_at",
            "scopes",
            "token",
            "user_agent",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_user_sessions_rapidly_read_select)

    public_user_notifications_rapidly_read_select = PGGrantTable(
        schema="public",
        table="user_notifications",
        columns=["last_read_notification_id", "user_id"],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_user_notifications_rapidly_read_select)

    public_shares_rapidly_read_select = PGGrantTable(
        schema="public",
        table="shares",
        columns=[
            "created_at",
            "deleted_at",
            "description",
            "id",
            "is_archived",
            "modified_at",
            "name",
            "search_vector",
            "user_metadata",
            "visibility",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_shares_rapidly_read_select)

    public_share_prices_rapidly_read_select = PGGrantTable(
        schema="public",
        table="share_prices",
        columns=[
            "amount_type",
            "cap_amount",
            "created_at",
            "deleted_at",
            "id",
            "is_archived",
            "maximum_amount",
            "meter_id",
            "minimum_amount",
            "modified_at",
            "preset_amount",
            "price_amount",
            "price_currency",
            "seat_tiers",
            "share_id",
            "source",
            "unit_amount",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_share_prices_rapidly_read_select)

    public_share_medias_rapidly_read_select = PGGrantTable(
        schema="public",
        table="share_medias",
        columns=[
            "created_at",
            "deleted_at",
            "file_id",
            "id",
            "modified_at",
            "order",
            "share_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_share_medias_rapidly_read_select)

    public_share_custom_fields_rapidly_read_select = PGGrantTable(
        schema="public",
        table="share_custom_fields",
        columns=[
            "created_at",
            "custom_field_id",
            "deleted_at",
            "id",
            "modified_at",
            "order",
            "required",
            "share_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_share_custom_fields_rapidly_read_select)

    public_payments_rapidly_read_select = PGGrantTable(
        schema="public",
        table="payments",
        columns=[
            "amount",
            "created_at",
            "currency",
            "customer_email",
            "decline_message",
            "decline_reason",
            "deleted_at",
            "id",
            "method",
            "method_metadata",
            "modified_at",
            "processor",
            "processor_id",
            "processor_metadata",
            "risk_level",
            "risk_score",
            "status",
            "wallet_id",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_payments_rapidly_read_select)

    public_payment_methods_rapidly_read_select = PGGrantTable(
        schema="public",
        table="payment_methods",
        columns=[
            "created_at",
            "customer_id",
            "deleted_at",
            "id",
            "method_metadata",
            "modified_at",
            "processor",
            "processor_id",
            "type",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_payment_methods_rapidly_read_select)

    public_oauth_accounts_rapidly_read_select = PGGrantTable(
        schema="public",
        table="oauth_accounts",
        columns=[
            "access_token",
            "account_email",
            "account_id",
            "account_username",
            "created_at",
            "deleted_at",
            "expires_at",
            "id",
            "modified_at",
            "platform",
            "refresh_token",
            "refresh_token_expires_at",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_oauth_accounts_rapidly_read_select)

    public_oauth2_tokens_rapidly_read_select = PGGrantTable(
        schema="public",
        table="oauth2_tokens",
        columns=[
            "access_token",
            "access_token_revoked_at",
            "client_id",
            "created_at",
            "deleted_at",
            "expires_in",
            "id",
            "issued_at",
            "modified_at",
            "nonce",
            "refresh_token",
            "refresh_token_revoked_at",
            "scope",
            "sub_type",
            "token_type",
            "user_id",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_oauth2_tokens_rapidly_read_select)

    public_oauth2_grants_rapidly_read_select = PGGrantTable(
        schema="public",
        table="oauth2_grants",
        columns=[
            "client_id",
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "scope",
            "user_id",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_oauth2_grants_rapidly_read_select)

    public_oauth2_clients_rapidly_read_select = PGGrantTable(
        schema="public",
        table="oauth2_clients",
        columns=[
            "client_id",
            "client_id_issued_at",
            "client_metadata",
            "client_secret",
            "client_secret_expires_at",
            "created_at",
            "deleted_at",
            "first_party",
            "id",
            "modified_at",
            "rate_limit_group",
            "registration_access_token",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_oauth2_clients_rapidly_read_select)

    public_oauth2_authorization_codes_rapidly_read_select = PGGrantTable(
        schema="public",
        table="oauth2_authorization_codes",
        columns=[
            "acr",
            "amr",
            "auth_time",
            "client_id",
            "code",
            "code_challenge",
            "code_challenge_method",
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "nonce",
            "redirect_uri",
            "response_type",
            "scope",
            "sub_type",
            "user_id",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_oauth2_authorization_codes_rapidly_read_select)

    public_notifications_rapidly_read_select = PGGrantTable(
        schema="public",
        table="notifications",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "payload",
            "type",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_notifications_rapidly_read_select)

    public_notification_recipients_rapidly_read_select = PGGrantTable(
        schema="public",
        table="notification_recipients",
        columns=[
            "created_at",
            "deleted_at",
            "expo_push_token",
            "id",
            "modified_at",
            "platform",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_notification_recipients_rapidly_read_select)

    public_members_rapidly_read_select = PGGrantTable(
        schema="public",
        table="members",
        columns=[
            "created_at",
            "customer_id",
            "deleted_at",
            "email",
            "external_id",
            "id",
            "modified_at",
            "name",
            "oauth_accounts",
            "role",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_members_rapidly_read_select)

    public_member_sessions_rapidly_read_select = PGGrantTable(
        schema="public",
        table="member_sessions",
        columns=[
            "created_at",
            "deleted_at",
            "expires_at",
            "id",
            "member_id",
            "modified_at",
            "return_url",
            "token",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_member_sessions_rapidly_read_select)

    public_login_codes_rapidly_read_select = PGGrantTable(
        schema="public",
        table="login_codes",
        columns=[
            "code_hash",
            "created_at",
            "deleted_at",
            "email",
            "expires_at",
            "id",
            "modified_at",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_login_codes_rapidly_read_select)

    public_files_rapidly_read_select = PGGrantTable(
        schema="public",
        table="files",
        columns=[
            "checksum_etag",
            "checksum_sha256_base64",
            "checksum_sha256_hex",
            "created_at",
            "deleted_at",
            "id",
            "is_enabled",
            "is_uploaded",
            "last_modified_at",
            "mime_type",
            "modified_at",
            "name",
            "path",
            "scan_result",
            "scan_status",
            "scanned_at",
            "service",
            "size",
            "storage_version",
            "version",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_files_rapidly_read_select)

    public_file_share_sessions_rapidly_read_select = PGGrantTable(
        schema="public",
        table="file_share_sessions",
        columns=[
            "activated_at",
            "completed_at",
            "created_at",
            "creator_ip_hash",
            "currency",
            "deleted_at",
            "download_count",
            "expires_at",
            "file_name",
            "file_size_bytes",
            "id",
            "long_slug",
            "max_downloads",
            "modified_at",
            "price_cents",
            "share_id",
            "short_slug",
            "status",
            "title",
            "ttl_seconds",
            "user_id",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_file_share_sessions_rapidly_read_select)

    public_file_share_reports_rapidly_read_select = PGGrantTable(
        schema="public",
        table="file_share_reports",
        columns=[
            "admin_notes",
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "reason",
            "reporter_ip_hash",
            "reviewed_at",
            "session_id",
            "status",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_file_share_reports_rapidly_read_select)

    public_file_share_payments_rapidly_read_select = PGGrantTable(
        schema="public",
        table="file_share_payments",
        columns=[
            "amount_cents",
            "buyer_email",
            "buyer_ip_hash",
            "buyer_name",
            "created_at",
            "currency",
            "customer_id",
            "deleted_at",
            "id",
            "modified_at",
            "payment_id",
            "payment_method_id",
            "platform_fee_cents",
            "session_id",
            "status",
            "stripe_checkout_session_id",
            "stripe_payment_intent_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_file_share_payments_rapidly_read_select)

    public_file_share_downloads_rapidly_read_select = PGGrantTable(
        schema="public",
        table="file_share_downloads",
        columns=[
            "created_at",
            "deleted_at",
            "downloader_ip_hash",
            "id",
            "modified_at",
            "session_id",
            "slot_number",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_file_share_downloads_rapidly_read_select)

    public_external_events_rapidly_read_select = PGGrantTable(
        schema="public",
        table="external_events",
        columns=[
            "created_at",
            "data",
            "deleted_at",
            "external_id",
            "handled_at",
            "id",
            "modified_at",
            "source",
            "task_name",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_external_events_rapidly_read_select)

    public_events_closure_rapidly_read_select = PGGrantTable(
        schema="public",
        table="events_closure",
        columns=["ancestor_id", "depth", "descendant_id"],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_events_closure_rapidly_read_select)

    public_events_rapidly_read_select = PGGrantTable(
        schema="public",
        table="events",
        columns=[
            "customer_id",
            "event_type_id",
            "external_customer_id",
            "external_id",
            "external_member_id",
            "id",
            "ingested_at",
            "member_id",
            "name",
            "parent_id",
            "root_id",
            "source",
            "timestamp",
            "user_metadata",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_events_rapidly_read_select)

    public_event_types_rapidly_read_select = PGGrantTable(
        schema="public",
        table="event_types",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "label",
            "label_property_selector",
            "modified_at",
            "name",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_event_types_rapidly_read_select)

    public_email_verification_rapidly_read_select = PGGrantTable(
        schema="public",
        table="email_verification",
        columns=[
            "created_at",
            "deleted_at",
            "email",
            "expires_at",
            "id",
            "modified_at",
            "token_hash",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_email_verification_rapidly_read_select)

    public_customers_rapidly_read_select = PGGrantTable(
        schema="public",
        table="customers",
        columns=[
            "billing_address",
            "billing_name",
            "created_at",
            "default_payment_method_id",
            "deleted_at",
            "email",
            "email_verified",
            "external_id",
            "id",
            "invoice_next_number",
            "legacy_user_id",
            "meters_dirtied_at",
            "meters_updated_at",
            "modified_at",
            "name",
            "oauth_accounts",
            "search_vector",
            "short_id",
            "stripe_customer_id",
            "type",
            "user_metadata",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_customers_rapidly_read_select)

    public_customer_sessions_rapidly_read_select = PGGrantTable(
        schema="public",
        table="customer_sessions",
        columns=[
            "created_at",
            "customer_id",
            "deleted_at",
            "expires_at",
            "id",
            "modified_at",
            "return_url",
            "token",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_customer_sessions_rapidly_read_select)

    public_customer_session_codes_rapidly_read_select = PGGrantTable(
        schema="public",
        table="customer_session_codes",
        columns=[
            "code",
            "created_at",
            "customer_id",
            "deleted_at",
            "email",
            "expires_at",
            "id",
            "modified_at",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_customer_session_codes_rapidly_read_select)

    public_custom_fields_rapidly_read_select = PGGrantTable(
        schema="public",
        table="custom_fields",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "name",
            "properties",
            "slug",
            "type",
            "user_metadata",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_custom_fields_rapidly_read_select)

    public_alembic_version_rapidly_read_select = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_alembic_version_rapidly_read_select)

    public_accounts_rapidly_read_select = PGGrantTable(
        schema="public",
        table="accounts",
        columns=[
            "account_type",
            "admin_id",
            "billing_additional_info",
            "billing_address",
            "billing_name",
            "billing_notes",
            "business_type",
            "campaign_id",
            "country",
            "created_at",
            "credit_balance",
            "currency",
            "data",
            "deleted_at",
            "email",
            "id",
            "is_charges_enabled",
            "is_details_submitted",
            "is_payouts_enabled",
            "modified_at",
            "next_review_threshold",
            "open_collective_slug",
            "platform_fee_fixed",
            "platform_fee_percent",
            "processor_fees_applicable",
            "status",
            "stripe_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_accounts_rapidly_read_select)

    # ### end Alembic commands ###
