"""add analytic_views table

Revision ID: aa2e64ab81f6
Revises: 27ed2e68876f
Create Date: 2026-05-20 22:42:15.273300

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "aa2e64ab81f6"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytic_views",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("query", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("analytic_views_created_by_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("analytic_views_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("analytic_views_workspace_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("analytic_views_pkey")),
    )
    op.create_index(
        op.f("ix_analytic_views_created_at"),
        "analytic_views",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytic_views_created_by_id"),
        "analytic_views",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytic_views_deleted_at"),
        "analytic_views",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytic_views_project_id"),
        "analytic_views",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytic_views_workspace_id"),
        "analytic_views",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analytic_views_workspace_id"), table_name="analytic_views")
    op.drop_index(op.f("ix_analytic_views_project_id"), table_name="analytic_views")
    op.drop_index(op.f("ix_analytic_views_deleted_at"), table_name="analytic_views")
    op.drop_index(op.f("ix_analytic_views_created_by_id"), table_name="analytic_views")
    op.drop_index(op.f("ix_analytic_views_created_at"), table_name="analytic_views")
    op.drop_table("analytic_views")
    # ### end Alembic commands ###
