"""add work_item_activities

Revision ID: 041f2d2b2a0e
Revises: 6fe332564f08
Create Date: 2026-05-12 20:37:59.247575

"""

import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

from rapidly.core.extensions.sqlalchemy.types import StringEnum
from rapidly.models.work_item_activity import WorkItemActivityVerb

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "041f2d2b2a0e"
down_revision = "6fe332564f08"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_project_module_work_items_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_module_work_items",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "module_id",
            "work_item_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_project_module_work_items_rapidly_read_select)

    public_project_modules_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_modules",
        columns=[
            "archived_at",
            "created_at",
            "deleted_at",
            "description",
            "id",
            "lead_id",
            "modified_at",
            "name",
            "project_id",
            "start_date",
            "status",
            "target_date",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_project_modules_rapidly_read_select)

    op.create_table(
        "work_item_activities",
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "verb",
            StringEnum(WorkItemActivityVerb, length=32),
            nullable=False,
        ),
        sa.Column("field", sa.String(length=64), nullable=True),
        sa.Column("old_value", sa.String(length=512), nullable=True),
        sa.Column("new_value", sa.String(length=512), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("comment_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("work_item_activities_actor_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["work_item_comments.id"],
            name=op.f("work_item_activities_comment_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("work_item_activities_work_item_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("work_item_activities_pkey")),
    )
    op.create_index(
        op.f("ix_work_item_activities_actor_id"),
        "work_item_activities",
        ["actor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_activities_comment_id"),
        "work_item_activities",
        ["comment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_activities_created_at"),
        "work_item_activities",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_activities_deleted_at"),
        "work_item_activities",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_activities_verb"),
        "work_item_activities",
        ["verb"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_activities_work_item_id"),
        "work_item_activities",
        ["work_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_work_item_activities_work_item_id"), table_name="work_item_activities"
    )
    op.drop_index(
        op.f("ix_work_item_activities_verb"), table_name="work_item_activities"
    )
    op.drop_index(
        op.f("ix_work_item_activities_deleted_at"), table_name="work_item_activities"
    )
    op.drop_index(
        op.f("ix_work_item_activities_created_at"), table_name="work_item_activities"
    )
    op.drop_index(
        op.f("ix_work_item_activities_comment_id"), table_name="work_item_activities"
    )
    op.drop_index(
        op.f("ix_work_item_activities_actor_id"), table_name="work_item_activities"
    )
    op.drop_table("work_item_activities")
    public_project_modules_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_modules",
        columns=[
            "archived_at",
            "created_at",
            "deleted_at",
            "description",
            "id",
            "lead_id",
            "modified_at",
            "name",
            "project_id",
            "start_date",
            "status",
            "target_date",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_project_modules_rapidly_read_select)

    public_project_module_work_items_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_module_work_items",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "module_id",
            "work_item_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_project_module_work_items_rapidly_read_select)

    # ### end Alembic commands ###
