"""add project_page_versions table

Revision ID: caeb55b77d39
Revises: 27ed2e68876f
Create Date: 2026-05-19 22:59:18.037833

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "caeb55b77d39"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_page_versions",
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "description_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("description_html", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("project_page_versions_author_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["project_pages.id"],
            name=op.f("project_page_versions_page_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_page_versions_pkey")),
        sa.UniqueConstraint(
            "page_id",
            "version_number",
            name="project_page_versions_page_id_version_number_key",
        ),
    )
    op.create_index(
        op.f("ix_project_page_versions_author_id"),
        "project_page_versions",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_page_versions_created_at"),
        "project_page_versions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_page_versions_deleted_at"),
        "project_page_versions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_page_versions_page_id"),
        "project_page_versions",
        ["page_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_page_versions_page_id"), table_name="project_page_versions"
    )
    op.drop_index(
        op.f("ix_project_page_versions_deleted_at"), table_name="project_page_versions"
    )
    op.drop_index(
        op.f("ix_project_page_versions_created_at"), table_name="project_page_versions"
    )
    op.drop_index(
        op.f("ix_project_page_versions_author_id"), table_name="project_page_versions"
    )
    op.drop_table("project_page_versions")
    # ### end Alembic commands ###
