"""add work_item_attachments table

Revision ID: be5645fe80ba
Revises: 27ed2e68876f
Create Date: 2026-05-19 23:50:32.988454

"""

import sqlalchemy as sa
from alembic import op

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "be5645fe80ba"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_item_attachments",
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("work_item_attachments_file_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("work_item_attachments_uploaded_by_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("work_item_attachments_work_item_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("work_item_attachments_pkey")),
        sa.UniqueConstraint(
            "work_item_id",
            "file_id",
            name="work_item_attachments_work_item_id_file_id_key",
        ),
    )
    op.create_index(
        op.f("ix_work_item_attachments_created_at"),
        "work_item_attachments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_attachments_deleted_at"),
        "work_item_attachments",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_attachments_file_id"),
        "work_item_attachments",
        ["file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_attachments_uploaded_by_id"),
        "work_item_attachments",
        ["uploaded_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_attachments_work_item_id"),
        "work_item_attachments",
        ["work_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_work_item_attachments_work_item_id"),
        table_name="work_item_attachments",
    )
    op.drop_index(
        op.f("ix_work_item_attachments_uploaded_by_id"),
        table_name="work_item_attachments",
    )
    op.drop_index(
        op.f("ix_work_item_attachments_file_id"), table_name="work_item_attachments"
    )
    op.drop_index(
        op.f("ix_work_item_attachments_deleted_at"), table_name="work_item_attachments"
    )
    op.drop_index(
        op.f("ix_work_item_attachments_created_at"), table_name="work_item_attachments"
    )
    op.drop_table("work_item_attachments")
    # ### end Alembic commands ###
