"""add work_item_reactions and work_item_comment_reactions tables

Revision ID: 89e5a25e399a
Revises: 27ed2e68876f
Create Date: 2026-05-20 00:28:52.056329

"""

import sqlalchemy as sa
from alembic import op

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "89e5a25e399a"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_item_reactions",
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("reaction", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("work_item_reactions_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("work_item_reactions_work_item_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("work_item_reactions_pkey")),
        sa.UniqueConstraint(
            "work_item_id",
            "user_id",
            "reaction",
            name="work_item_reactions_work_item_id_user_id_reaction_key",
        ),
    )
    op.create_index(
        op.f("ix_work_item_reactions_created_at"),
        "work_item_reactions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_reactions_deleted_at"),
        "work_item_reactions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_reactions_user_id"),
        "work_item_reactions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_reactions_work_item_id"),
        "work_item_reactions",
        ["work_item_id"],
        unique=False,
    )
    op.create_table(
        "work_item_comment_reactions",
        sa.Column("comment_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("reaction", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["work_item_comments.id"],
            name=op.f("work_item_comment_reactions_comment_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("work_item_comment_reactions_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("work_item_comment_reactions_pkey")),
        sa.UniqueConstraint(
            "comment_id",
            "user_id",
            "reaction",
            name="work_item_comment_reactions_comment_id_user_id_reaction_key",
        ),
    )
    op.create_index(
        op.f("ix_work_item_comment_reactions_comment_id"),
        "work_item_comment_reactions",
        ["comment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_comment_reactions_created_at"),
        "work_item_comment_reactions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_comment_reactions_deleted_at"),
        "work_item_comment_reactions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_comment_reactions_user_id"),
        "work_item_comment_reactions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_work_item_comment_reactions_user_id"),
        table_name="work_item_comment_reactions",
    )
    op.drop_index(
        op.f("ix_work_item_comment_reactions_deleted_at"),
        table_name="work_item_comment_reactions",
    )
    op.drop_index(
        op.f("ix_work_item_comment_reactions_created_at"),
        table_name="work_item_comment_reactions",
    )
    op.drop_index(
        op.f("ix_work_item_comment_reactions_comment_id"),
        table_name="work_item_comment_reactions",
    )
    op.drop_table("work_item_comment_reactions")
    op.drop_index(
        op.f("ix_work_item_reactions_work_item_id"), table_name="work_item_reactions"
    )
    op.drop_index(
        op.f("ix_work_item_reactions_user_id"), table_name="work_item_reactions"
    )
    op.drop_index(
        op.f("ix_work_item_reactions_deleted_at"), table_name="work_item_reactions"
    )
    op.drop_index(
        op.f("ix_work_item_reactions_created_at"), table_name="work_item_reactions"
    )
    op.drop_table("work_item_reactions")
    # ### end Alembic commands ###
