"""add project_cycle_user_properties and project_module_user_properties

Revision ID: 6ee938ab930a
Revises: 27ed2e68876f
Create Date: 2026-05-20 20:46:26.617370

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "6ee938ab930a"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_cycle_user_properties",
        sa.Column("cycle_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "display_filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "display_properties",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["project_cycles.id"],
            name=op.f("project_cycle_user_properties_cycle_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("project_cycle_user_properties_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_cycle_user_properties_pkey")),
        sa.UniqueConstraint(
            "cycle_id",
            "user_id",
            name="project_cycle_user_properties_cycle_id_user_id_key",
        ),
    )
    op.create_index(
        op.f("ix_project_cycle_user_properties_created_at"),
        "project_cycle_user_properties",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_cycle_user_properties_cycle_id"),
        "project_cycle_user_properties",
        ["cycle_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_cycle_user_properties_deleted_at"),
        "project_cycle_user_properties",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_cycle_user_properties_user_id"),
        "project_cycle_user_properties",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "project_module_user_properties",
        sa.Column("module_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "display_filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "display_properties",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["project_modules.id"],
            name=op.f("project_module_user_properties_module_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("project_module_user_properties_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_module_user_properties_pkey")),
        sa.UniqueConstraint(
            "module_id",
            "user_id",
            name="project_module_user_properties_module_id_user_id_key",
        ),
    )
    op.create_index(
        op.f("ix_project_module_user_properties_created_at"),
        "project_module_user_properties",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_module_user_properties_deleted_at"),
        "project_module_user_properties",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_module_user_properties_module_id"),
        "project_module_user_properties",
        ["module_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_module_user_properties_user_id"),
        "project_module_user_properties",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_module_user_properties_user_id"),
        table_name="project_module_user_properties",
    )
    op.drop_index(
        op.f("ix_project_module_user_properties_module_id"),
        table_name="project_module_user_properties",
    )
    op.drop_index(
        op.f("ix_project_module_user_properties_deleted_at"),
        table_name="project_module_user_properties",
    )
    op.drop_index(
        op.f("ix_project_module_user_properties_created_at"),
        table_name="project_module_user_properties",
    )
    op.drop_table("project_module_user_properties")
    op.drop_index(
        op.f("ix_project_cycle_user_properties_user_id"),
        table_name="project_cycle_user_properties",
    )
    op.drop_index(
        op.f("ix_project_cycle_user_properties_deleted_at"),
        table_name="project_cycle_user_properties",
    )
    op.drop_index(
        op.f("ix_project_cycle_user_properties_cycle_id"),
        table_name="project_cycle_user_properties",
    )
    op.drop_index(
        op.f("ix_project_cycle_user_properties_created_at"),
        table_name="project_cycle_user_properties",
    )
    op.drop_table("project_cycle_user_properties")
    # ### end Alembic commands ###
