"""add project_user_properties table

Revision ID: e78c01deedb8
Revises: 27ed2e68876f
Create Date: 2026-05-20 20:25:57.518458

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "e78c01deedb8"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_user_properties",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "display_filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "display_properties",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("project_user_properties_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("project_user_properties_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_user_properties_pkey")),
        sa.UniqueConstraint(
            "project_id",
            "user_id",
            name="project_user_properties_project_id_user_id_key",
        ),
    )
    op.create_index(
        op.f("ix_project_user_properties_created_at"),
        "project_user_properties",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_user_properties_deleted_at"),
        "project_user_properties",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_user_properties_project_id"),
        "project_user_properties",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_user_properties_user_id"),
        "project_user_properties",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_user_properties_user_id"), table_name="project_user_properties"
    )
    op.drop_index(
        op.f("ix_project_user_properties_project_id"),
        table_name="project_user_properties",
    )
    op.drop_index(
        op.f("ix_project_user_properties_deleted_at"),
        table_name="project_user_properties",
    )
    op.drop_index(
        op.f("ix_project_user_properties_created_at"),
        table_name="project_user_properties",
    )
    op.drop_table("project_user_properties")
    # ### end Alembic commands ###
