"""add work_item_types table and work_items.type_id

Revision ID: 334977c761f3
Revises: 27ed2e68876f
Create Date: 2026-05-20 00:40:53.830329

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "334977c761f3"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_item_types",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "logo_props", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_epic", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("work_item_types_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("work_item_types_pkey")),
        sa.UniqueConstraint(
            "project_id", "name", name="work_item_types_project_id_name_key"
        ),
    )
    op.create_index(
        op.f("ix_work_item_types_created_at"),
        "work_item_types",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_types_deleted_at"),
        "work_item_types",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_types_project_id"),
        "work_item_types",
        ["project_id"],
        unique=False,
    )
    op.add_column("work_items", sa.Column("type_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_work_items_type_id"), "work_items", ["type_id"], unique=False
    )
    op.create_foreign_key(
        op.f("work_items_type_id_fkey"),
        "work_items",
        "work_item_types",
        ["type_id"],
        ["id"],
        ondelete="set null",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("work_items_type_id_fkey"), "work_items", type_="foreignkey"
    )
    op.drop_index(op.f("ix_work_items_type_id"), table_name="work_items")
    op.drop_column("work_items", "type_id")
    op.drop_index(op.f("ix_work_item_types_project_id"), table_name="work_item_types")
    op.drop_index(op.f("ix_work_item_types_deleted_at"), table_name="work_item_types")
    op.drop_index(op.f("ix_work_item_types_created_at"), table_name="work_item_types")
    op.drop_table("work_item_types")
    # ### end Alembic commands ###
