"""add project_views table

Revision ID: e1726391eb6a
Revises: 27ed2e68876f
Create Date: 2026-05-19 22:36:00.484570

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Rapidly Custom Imports
from rapidly.core.extensions.sqlalchemy.types import StringEnum
from rapidly.models.project_view import ProjectViewAccess

# revision identifiers, used by Alembic.
revision = "e1726391eb6a"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_views",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "display_filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "display_properties",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "access",
            StringEnum(ProjectViewAccess, length=16),
            nullable=False,
        ),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Float(), nullable=False),
        sa.Column("archived_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("project_views_owner_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("project_views_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_views_pkey")),
    )
    op.create_index(
        op.f("ix_project_views_archived_at"),
        "project_views",
        ["archived_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_views_created_at"),
        "project_views",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_views_deleted_at"),
        "project_views",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_views_owner_id"), "project_views", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_views_project_id"),
        "project_views",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_views_project_id"), table_name="project_views")
    op.drop_index(op.f("ix_project_views_owner_id"), table_name="project_views")
    op.drop_index(op.f("ix_project_views_deleted_at"), table_name="project_views")
    op.drop_index(op.f("ix_project_views_created_at"), table_name="project_views")
    op.drop_index(op.f("ix_project_views_archived_at"), table_name="project_views")
    op.drop_table("project_views")
    # ### end Alembic commands ###
