"""add rate_limit_group to projects

Revision ID: 9c13881d3227
Revises: 89780c8c1f1f
Create Date: 2026-05-10 21:45:08.245552

"""

import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text

from rapidly.core.extensions.sqlalchemy.types import StringEnum
from rapidly.enums import RateLimitGroup

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "9c13881d3227"
down_revision = "89780c8c1f1f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_project_estimate_points_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_estimate_points",
        columns=[
            "created_at",
            "deleted_at",
            "description",
            "estimate_id",
            "id",
            "key",
            "modified_at",
            "value",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_project_estimate_points_rapidly_read_select)

    public_project_estimates_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_estimates",
        columns=[
            "created_at",
            "deleted_at",
            "description",
            "id",
            "is_active",
            "modified_at",
            "name",
            "project_id",
            "type",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_project_estimates_rapidly_read_select)

    public_project_labels_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_labels",
        columns=[
            "color",
            "created_at",
            "deleted_at",
            "description",
            "id",
            "modified_at",
            "name",
            "parent_id",
            "project_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_project_labels_rapidly_read_select)

    public_project_members_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_members",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "project_id",
            "role",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_project_members_rapidly_read_select)

    public_project_states_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_states",
        columns=[
            "color",
            "created_at",
            "deleted_at",
            "description",
            "group",
            "id",
            "is_default",
            "modified_at",
            "name",
            "project_id",
            "sequence",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_project_states_rapidly_read_select)

    public_projects_rapidly_read_select = PGGrantTable(
        schema="public",
        table="projects",
        columns=[
            "archived_at",
            "color",
            "cover_image_url",
            "created_at",
            "deleted_at",
            "description",
            "emoji",
            "id",
            "identifier",
            "is_cycles_enabled",
            "is_intake_enabled",
            "is_modules_enabled",
            "is_pages_enabled",
            "is_views_enabled",
            "modified_at",
            "name",
            "owner_id",
            "slug",
            "visibility",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_projects_rapidly_read_select)

    op.add_column(
        "projects",
        sa.Column(
            "rate_limit_group",
            StringEnum(RateLimitGroup, length=16),
            nullable=False,
            server_default=RateLimitGroup.default.value,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "rate_limit_group")
    public_projects_rapidly_read_select = PGGrantTable(
        schema="public",
        table="projects",
        columns=[
            "archived_at",
            "color",
            "cover_image_url",
            "created_at",
            "deleted_at",
            "description",
            "emoji",
            "id",
            "identifier",
            "is_cycles_enabled",
            "is_intake_enabled",
            "is_modules_enabled",
            "is_pages_enabled",
            "is_views_enabled",
            "modified_at",
            "name",
            "owner_id",
            "slug",
            "visibility",
            "workspace_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_projects_rapidly_read_select)

    public_project_states_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_states",
        columns=[
            "color",
            "created_at",
            "deleted_at",
            "description",
            "group",
            "id",
            "is_default",
            "modified_at",
            "name",
            "project_id",
            "sequence",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_project_states_rapidly_read_select)

    public_project_members_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_members",
        columns=[
            "created_at",
            "deleted_at",
            "id",
            "modified_at",
            "project_id",
            "role",
            "user_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_project_members_rapidly_read_select)

    public_project_labels_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_labels",
        columns=[
            "color",
            "created_at",
            "deleted_at",
            "description",
            "id",
            "modified_at",
            "name",
            "parent_id",
            "project_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_project_labels_rapidly_read_select)

    public_project_estimates_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_estimates",
        columns=[
            "created_at",
            "deleted_at",
            "description",
            "id",
            "is_active",
            "modified_at",
            "name",
            "project_id",
            "type",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_project_estimates_rapidly_read_select)

    public_project_estimate_points_rapidly_read_select = PGGrantTable(
        schema="public",
        table="project_estimate_points",
        columns=[
            "created_at",
            "deleted_at",
            "description",
            "estimate_id",
            "id",
            "key",
            "modified_at",
            "value",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_project_estimate_points_rapidly_read_select)

    # ### end Alembic commands ###
