"""add project_deploy_boards table

Revision ID: f6a2365f0b80
Revises: 27ed2e68876f
Create Date: 2026-05-21 19:47:13.665966

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "f6a2365f0b80"
down_revision = "27ed2e68876f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_deploy_boards",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("show_comments", sa.Boolean(), nullable=False),
        sa.Column("show_reactions", sa.Boolean(), nullable=False),
        sa.Column("show_votes", sa.Boolean(), nullable=False),
        sa.Column("show_intake_form", sa.Boolean(), nullable=False),
        sa.Column(
            "view_props", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("project_deploy_boards_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_deploy_boards_pkey")),
        sa.UniqueConstraint("project_id", name="project_deploy_boards_project_id_key"),
        sa.UniqueConstraint("token", name="project_deploy_boards_token_key"),
    )
    op.create_index(
        op.f("ix_project_deploy_boards_created_at"),
        "project_deploy_boards",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_deploy_boards_deleted_at"),
        "project_deploy_boards",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_deploy_boards_project_id"),
        "project_deploy_boards",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_deploy_boards_project_id"), table_name="project_deploy_boards"
    )
    op.drop_index(
        op.f("ix_project_deploy_boards_deleted_at"), table_name="project_deploy_boards"
    )
    op.drop_index(
        op.f("ix_project_deploy_boards_created_at"), table_name="project_deploy_boards"
    )
    op.drop_table("project_deploy_boards")
    # ### end Alembic commands ###
