"""add project_pages

Revision ID: 27ed2e68876f
Revises: 041f2d2b2a0e
Create Date: 2026-05-12 21:40:06.089569

"""

import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

from rapidly.core.extensions.sqlalchemy.types import StringEnum
from enum import StrEnum


class ProjectPageAccess(StrEnum):
    """Inlined for M1.5 post-deletion compatibility."""
    private = "private"
    public = "public"

# Rapidly Custom Imports

# revision identifiers, used by Alembic.
revision = "27ed2e68876f"
down_revision = "041f2d2b2a0e"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_work_item_activities_rapidly_read_select = PGGrantTable(
        schema="public",
        table="work_item_activities",
        columns=[
            "actor_id",
            "comment_id",
            "created_at",
            "deleted_at",
            "field",
            "id",
            "modified_at",
            "new_value",
            "old_value",
            "payload",
            "verb",
            "work_item_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_work_item_activities_rapidly_read_select)

    op.create_table(
        "project_pages",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "description_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("description_html", sa.Text(), nullable=True),
        sa.Column("description_binary", sa.LargeBinary(), nullable=True),
        sa.Column(
            "access",
            StringEnum(ProjectPageAccess, length=16),
            nullable=False,
        ),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("project_pages_owner_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["project_pages.id"],
            name=op.f("project_pages_parent_id_fkey"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("project_pages_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_pages_pkey")),
        sa.UniqueConstraint(
            "project_id", "slug", name="project_pages_project_id_slug_key"
        ),
    )
    op.create_index(
        op.f("ix_project_pages_archived_at"),
        "project_pages",
        ["archived_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_pages_created_at"),
        "project_pages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_pages_deleted_at"),
        "project_pages",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_pages_owner_id"), "project_pages", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_pages_parent_id"), "project_pages", ["parent_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_pages_project_id"),
        "project_pages",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_pages_project_id"), table_name="project_pages")
    op.drop_index(op.f("ix_project_pages_parent_id"), table_name="project_pages")
    op.drop_index(op.f("ix_project_pages_owner_id"), table_name="project_pages")
    op.drop_index(op.f("ix_project_pages_deleted_at"), table_name="project_pages")
    op.drop_index(op.f("ix_project_pages_created_at"), table_name="project_pages")
    op.drop_index(op.f("ix_project_pages_archived_at"), table_name="project_pages")
    op.drop_table("project_pages")
    public_work_item_activities_rapidly_read_select = PGGrantTable(
        schema="public",
        table="work_item_activities",
        columns=[
            "actor_id",
            "comment_id",
            "created_at",
            "deleted_at",
            "field",
            "id",
            "modified_at",
            "new_value",
            "old_value",
            "payload",
            "verb",
            "work_item_id",
        ],
        role="rapidly_read",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_work_item_activities_rapidly_read_select)

    # ### end Alembic commands ###
