import { LegalPage } from '@/components/Landing/LegalPage'
import { CONFIG } from '@/utils/config'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Data Processing Agreement',
  description:
    'Data Processing Agreement (DPA) for the Rapidly platform under GDPR Article 28.',
  openGraph: {
    siteName: 'Rapidly',
    type: 'website',
    images: [{ url: CONFIG.OG_IMAGE_URL, width: 1200, height: 630 }],
  },
}

const sections = [
  {
    title: '1. Definitions',
    content: `In this Data Processing Agreement ("DPA"), the following terms have the meanings set out below. Capitalised terms not defined here have the meanings given in the <a href="/legal/terms" class="underline">Terms of Use</a> or the <a href="/legal/privacy" class="underline">Privacy Policy</a>.<br/><br/><ul class="list-disc pl-6 space-y-1"><li><strong>"Controller"</strong> means the entity that determines the purposes and means of the processing of Personal Data — in most cases, the workspace owner or administrator using the Services.</li><li><strong>"Processor"</strong> means the entity that processes Personal Data on behalf of the Controller — in this case, Rapidly Software Ltd.</li><li><strong>"Personal Data"</strong> means any information relating to an identified or identifiable natural person, as defined in Article 4(1) of the GDPR.</li><li><strong>"Processing"</strong> means any operation performed on Personal Data, as defined in Article 4(2) of the GDPR.</li><li><strong>"Sub-processor"</strong> means any third party engaged by Rapidly to process Personal Data on behalf of the Controller.</li><li><strong>"Data Breach"</strong> means a breach of security leading to the accidental or unlawful destruction, loss, alteration, unauthorised disclosure of, or access to, Personal Data.</li><li><strong>"GDPR"</strong> means Regulation (EU) 2016/679 (General Data Protection Regulation).</li><li><strong>"UK GDPR"</strong> means the GDPR as retained in United Kingdom law by the European Union (Withdrawal) Act 2018.</li><li><strong>"SCCs"</strong> means the Standard Contractual Clauses adopted by the European Commission (Implementing Decision 2021/914).</li></ul>`,
  },
  {
    title: '2. Scope & Relationship',
    content: `<strong>Applicability.</strong> This DPA applies when Rapidly processes Personal Data on behalf of the Controller in the course of providing the Services. This DPA supplements and is incorporated into the <a href="/legal/terms" class="underline">Terms of Use</a>. In the event of any conflict between this DPA and the Terms of Use on matters of data protection, this DPA shall prevail.<br/><br/><strong>Roles.</strong> The workspace owner or administrator is the Controller. Rapidly is the Processor. The Controller determines the purposes and means of processing; Rapidly processes Personal Data only on behalf of and in accordance with the Controller's documented instructions.<br/><br/><strong>Duration.</strong> This DPA remains in effect for the duration of the Controller's use of the Services and continues until all Personal Data has been deleted or returned in accordance with Section 9.`,
  },
  {
    title: '3. Description of Processing',
    content: `<strong>Subject Matter:</strong> Provision of the Rapidly platform, including file sharing, customer management, analytics, and payment facilitation.<br/><br/><strong>Categories of Data Subjects:</strong><ul class="list-disc pl-6 space-y-1 mt-2"><li>End users and visitors of the Controller's workspace</li><li>Customers who interact with the Controller's workspace</li><li>Workspace members and collaborators</li><li>File share recipients</li></ul><br/><strong>Categories of Personal Data:</strong><ul class="list-disc pl-6 space-y-1 mt-2"><li>Contact information (name, email address)</li><li>Billing and payment data (processed via Stripe; Rapidly stores only metadata)</li><li>File sharing metadata (hashed IP addresses, download counts, timestamps, checksums)</li><li>Customer/CRM data (names, emails, billing addresses, external IDs, custom field responses)</li><li>Usage data (page views, feature usage, session data)</li><li>Device and technical data (IP address, browser type, operating system)</li></ul><br/><strong>Special Category Data:</strong> The Controller may upload or collect special category data (e.g., health, financial, or biometric data) through files or custom fields. The Controller is solely responsible for ensuring a lawful basis exists for processing any such data and for informing Rapidly if special category data is being processed.<br/><br/><strong>Purpose of Processing:</strong> To provide, maintain, secure, and improve the Services as described in the Terms of Use and as instructed by the Controller.`,
  },
  {
    title: '4. Controller Obligations',
    content: `The Controller shall:<br/><br/><ul class="list-disc pl-6 space-y-1"><li>Ensure that its instructions to Rapidly comply with all applicable data protection laws;</li><li>Have a lawful basis for processing Personal Data and for transferring it to Rapidly;</li><li>Provide all necessary notices to, and obtain all necessary consents or authorisations from, data subjects as required by applicable law;</li><li>Conduct Data Protection Impact Assessments (DPIAs) where required under Article 35 of the GDPR; and</li><li>Promptly notify Rapidly if it becomes aware of any Data Breach or security incident affecting Personal Data processed through the Services.</li></ul>`,
  },
  {
    title: '5. Processor Obligations',
    content: `Rapidly shall:<br/><br/><strong>(a) Instructions.</strong> Process Personal Data only on the Controller's documented instructions, including with regard to international data transfers, unless required to do so by EU or member state law — in which case Rapidly will inform the Controller of the legal requirement before processing (unless prohibited by law).<br/><br/><strong>(b) Confidentiality.</strong> Ensure that all persons authorised to process Personal Data are bound by appropriate confidentiality obligations, whether contractual or statutory.<br/><br/><strong>(c) Security.</strong> Implement and maintain appropriate technical and organisational measures to protect Personal Data, as described in Section 7 of this DPA and as required by Article 32 of the GDPR.<br/><br/><strong>(d) Sub-processors.</strong> Not engage any Sub-processor without prior compliance with Section 6 of this DPA.<br/><br/><strong>(e) Data Subject Rights.</strong> Assist the Controller, by appropriate technical and organisational measures and insofar as possible, in fulfilling the Controller's obligations to respond to data subject requests under Articles 15–22 of the GDPR (access, rectification, erasure, restriction, portability, objection).<br/><br/><strong>(f) Compliance Assistance.</strong> Assist the Controller in ensuring compliance with obligations under Articles 32–36 of the GDPR (security, breach notification, DPIAs, prior consultation with supervisory authorities), taking into account the nature of processing and information available to Rapidly.<br/><br/><strong>(g) Deletion/Return.</strong> At the Controller's choice, delete or return all Personal Data after the end of the provision of Services, and delete existing copies unless EU or member state law requires continued storage. See Section 9 for details.<br/><br/><strong>(h) Audit.</strong> Make available to the Controller all information necessary to demonstrate compliance with GDPR Article 28, and allow for and contribute to audits and inspections conducted by the Controller or an auditor mandated by the Controller. See Section 10 for details.`,
  },
  {
    title: '6. Sub-processors',
    content: `<strong>General Authorisation.</strong> The Controller grants Rapidly a general written authorisation to engage Sub-processors for the provision of the Services.<br/><br/><strong>Current Sub-processors.</strong> A list of current Sub-processors is maintained and available upon request by contacting <a href="mailto:data@rapidly.tech" class="underline">data@rapidly.tech</a>. Current Sub-processors include:<ul class="list-disc pl-6 space-y-1 mt-2"><li><strong>Cloud Infrastructure Provider</strong> — hosting, compute, storage (EU/US regions)</li><li><strong>Stripe, Inc.</strong> — payment processing (US, certified under EU-US Data Privacy Framework)</li><li><strong>Email Delivery Service</strong> — transactional and notification emails</li><li><strong>Sentry</strong> — error tracking and monitoring</li><li><strong>ClamAV</strong> — malware scanning (self-hosted)</li></ul><br/><strong>Notification of Changes.</strong> Rapidly will notify the Controller by email at least 30 days before engaging any new Sub-processor or replacing an existing one. The notification will include the Sub-processor's name, location, and description of processing.<br/><br/><strong>Objection Right.</strong> The Controller may object to a new Sub-processor within 14 days of notification by providing written reasons to <a href="mailto:data@rapidly.tech" class="underline">data@rapidly.tech</a>. Rapidly will make reasonable efforts to address the objection. If the objection cannot be resolved, the Controller may terminate the affected Services without penalty.<br/><br/><strong>Flow-Down Obligations.</strong> Rapidly shall impose on each Sub-processor, by way of contract, data protection obligations no less protective than those set out in this DPA, in accordance with Article 28(4) of the GDPR. Rapidly remains fully liable to the Controller for the performance of each Sub-processor's obligations.`,
  },
  {
    title: '7. Security Measures',
    content: `Rapidly implements and maintains the following technical and organisational measures to protect Personal Data, in accordance with Article 32 of the GDPR:<br/><br/><strong>Encryption:</strong><ul class="list-disc pl-6 space-y-1 mt-2"><li>TLS 1.2+ for all data in transit</li><li>AES-256 encryption for file transfers</li><li>Client-side OpenPGP encryption for secret messages</li><li>Encryption at rest for stored data</li></ul><br/><strong>Access Controls:</strong><ul class="list-disc pl-6 space-y-1 mt-2"><li>Role-based access controls (RBAC) with scope-based permissions</li><li>Least-privilege access for all employees and systems</li><li>Multi-factor authentication available for user accounts</li><li>API token and workspace access token management</li></ul><br/><strong>Infrastructure:</strong><ul class="list-disc pl-6 space-y-1 mt-2"><li>Hosted on industry-standard cloud infrastructure</li><li>Network firewalls and intrusion detection systems</li><li>Regular security patching and updates</li><li>Automated malware scanning (ClamAV) for uploaded files</li></ul><br/><strong>Monitoring & Logging:</strong><ul class="list-disc pl-6 space-y-1 mt-2"><li>Structured logging with audit trails</li><li>Automated security monitoring and anomaly detection</li><li>Rate limiting on all public endpoints</li></ul><br/><strong>Organisational:</strong><ul class="list-disc pl-6 space-y-1 mt-2"><li>Confidentiality obligations for all personnel</li><li>Security awareness and data protection training</li><li>Incident response plan and procedures</li></ul>`,
  },
  {
    title: '8. Data Breach Notification',
    content: `<strong>Notification to Controller.</strong> Rapidly shall notify the Controller without undue delay, and in any event within 48 hours, after becoming aware of a Data Breach affecting Personal Data processed on behalf of the Controller.<br/><br/><strong>Content of Notification.</strong> The notification shall include, to the extent available:<ul class="list-disc pl-6 space-y-1 mt-2"><li>A description of the nature of the Data Breach, including the categories and approximate number of data subjects and Personal Data records affected;</li><li>The name and contact details of Rapidly's point of contact;</li><li>A description of the likely consequences of the Data Breach;</li><li>A description of the measures taken or proposed to address the Data Breach, including measures to mitigate its possible adverse effects.</li></ul><br/><strong>Controller's Obligations.</strong> The Controller is responsible for notifying the relevant supervisory authority within 72 hours of becoming aware of a Data Breach (where required under Article 33 of the GDPR) and for notifying affected data subjects where required under Article 34.<br/><br/><strong>Cooperation.</strong> Rapidly shall cooperate with the Controller and provide reasonable assistance in investigating, mitigating, and remediating the Data Breach, and in fulfilling the Controller's notification obligations.`,
  },
  {
    title: '9. Data Deletion & Return',
    content: `<strong>Upon Termination.</strong> Upon termination or expiry of the Services, and at the Controller's written request, Rapidly shall either:<ul class="list-disc pl-6 space-y-1 mt-2"><li><strong>Return</strong> all Personal Data to the Controller in a structured, commonly used, machine-readable format (e.g., CSV or JSON export); or</li><li><strong>Delete</strong> all Personal Data, including all copies, from Rapidly's systems and those of its Sub-processors.</li></ul><br/><strong>Timeline.</strong> Rapidly will complete deletion or return within 30 days of receiving the Controller's instruction. Rapidly will confirm deletion in writing upon request.<br/><br/><strong>Exceptions.</strong> Rapidly may retain Personal Data to the extent required by applicable EU or member state law (e.g., tax records, legal holds). In such cases, Rapidly will inform the Controller of the legal requirement and will continue to protect the retained data in accordance with this DPA.<br/><br/><strong>Automatic Deletion.</strong> Certain data is automatically deleted by the Services in the ordinary course of operation:<ul class="list-disc pl-6 space-y-1 mt-2"><li>Secret messages/files: deleted upon retrieval or expiration</li><li>File sharing metadata: hashed IPs retained for up to 12 months</li><li>Server logs: retained for up to 90 days</li><li>Account data: deleted 30 days after account deletion</li></ul>`,
  },
  {
    title: '10. Audits',
    content: `<strong>Information.</strong> Rapidly shall make available to the Controller all information reasonably necessary to demonstrate compliance with the obligations set out in this DPA and GDPR Article 28.<br/><br/><strong>Audit Rights.</strong> The Controller (or an independent third-party auditor appointed by the Controller) may conduct audits and inspections of Rapidly's data processing activities, subject to the following conditions:<ul class="list-disc pl-6 space-y-1 mt-2"><li>The Controller shall provide at least 30 days' prior written notice;</li><li>Audits shall be conducted during normal business hours and shall not unreasonably disrupt Rapidly's operations;</li><li>The Controller shall bear the costs of the audit (unless the audit reveals material non-compliance by Rapidly);</li><li>The auditor must agree to reasonable confidentiality obligations;</li><li>Audits shall be limited to once per 12-month period, unless required by a supervisory authority or triggered by a Data Breach.</li></ul><br/><strong>Compliance Reports.</strong> Where available, Rapidly may satisfy audit requests by providing relevant compliance certifications, audit reports, or summaries prepared by independent third-party auditors.`,
  },
  {
    title: '11. International Data Transfers',
    content: `<strong>Transfer Locations.</strong> Personal Data may be transferred to and processed in the United States and other countries where Rapidly's infrastructure providers and Sub-processors operate.<br/><br/><strong>Transfer Mechanisms.</strong> For transfers of Personal Data from the EEA, UK, or Switzerland to countries without an adequate level of data protection, Rapidly relies on:<ul class="list-disc pl-6 space-y-1 mt-2"><li><strong>Standard Contractual Clauses (SCCs)</strong> — Module 2 (Controller-to-Processor) as adopted by the European Commission (Implementing Decision 2021/914), which are hereby incorporated by reference into this DPA;</li><li><strong>EU-US Data Privacy Framework</strong> — for transfers to US-based Sub-processors certified under the DPF;</li><li><strong>UK International Data Transfer Addendum (IDTA)</strong> — for transfers subject to the UK GDPR.</li></ul><br/><strong>Transfer Impact Assessments.</strong> Rapidly maintains Transfer Impact Assessments (TIAs) for its international data transfers and will make these available to the Controller upon request.<br/><br/><strong>Supplementary Measures.</strong> In addition to contractual safeguards, Rapidly implements supplementary technical measures including encryption in transit and at rest, pseudonymisation (IP hashing), and access controls to protect transferred data.`,
  },
  {
    title: '12. Liability',
    content: `Each party's liability under this DPA is subject to the limitations and exclusions set out in the <a href="/legal/terms" class="underline">Terms of Use</a>, except that:<ul class="list-disc pl-6 space-y-1 mt-2"><li>Neither party's liability for breaches of its data protection obligations under this DPA or applicable law (including GDPR) shall be limited in a manner that would prevent the other party from recovering direct damages caused by such breach;</li><li>Nothing in this DPA limits either party's liability for fraud, gross negligence, willful misconduct, or any liability that cannot be excluded under applicable law.</li></ul>`,
  },
  {
    title: '13. General',
    content: `<strong>Governing Law.</strong> This DPA is governed by the laws of Ireland. If the Controller is subject to the UK GDPR, the provisions of this DPA shall be interpreted in accordance with UK GDPR requirements.<br/><br/><strong>Amendments.</strong> Rapidly may update this DPA from time to time to reflect changes in law, regulatory guidance, or our processing practices. Material changes will be notified to the Controller at least 30 days in advance.<br/><br/><strong>Severability.</strong> If any provision of this DPA is found to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.<br/><br/><strong>Entire Agreement on Data Processing.</strong> This DPA, together with the Terms of Use and Privacy Policy, constitutes the complete agreement between the parties regarding the processing of Personal Data.`,
  },
  {
    title: '14. Contact',
    content: `For questions, requests, or notifications relating to this DPA, please contact:<br/><br/><strong>Rapidly Software Ltd.</strong><br/>Cork, Ireland<br/>Email: <a href="mailto:data@rapidly.tech" class="underline">data@rapidly.tech</a>`,
  },
]

export default function DPAPage() {
  return (
    <LegalPage
      icon="Shield"
      title="Data Processing Agreement"
      effectiveDate="April 2, 2026"
      intro='This Data Processing Agreement ("DPA") forms part of the Terms of Use between Rapidly Software Ltd. ("Rapidly," "Processor") and the workspace owner or administrator ("Controller") who uses the Rapidly platform. This DPA sets out the terms under which Rapidly processes Personal Data on behalf of the Controller, in compliance with GDPR Article 28 and applicable data protection laws.'
      sections={sections}
    />
  )
}
