name: Release packages

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        working-directory: ${{ github.workspace }}/clients

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
        with:
          package_json_file: clients/package.json

      - name: Setup Node.js environment
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: clients/.node-version
          cache: "pnpm"
          cache-dependency-path: "clients/pnpm-lock.yaml"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        # Pin to last known working version (see: https://github.com/changesets/action/issues/501)
        uses: changesets/action@001cd79f0a536e733315164543a727bdf2d70aff # v1.5.1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release-packages
          cwd: ${{ github.workspace }}/clients
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RAPIDLY_CHECKOUT_EMBED_SCRIPT_ALLOWED_ORIGINS: "https://rapidly.tech,https://sandbox.rapidly.tech"
